Repository microsoft/vcpkg, pull requests merged in 2019-03, with the labels that each got.

#5057 [nanopb] Add new port
  ports/nanopb/CONTROL
  ports/nanopb/portfile.cmake
  ports/nanopb/shared-lib.patch
Labels: wip

#5532 [pthreads]Modify library name "pthreadsVC2" to correct name "pthreadVC2"
  ports/flint/CONTROL
  ports/flint/dll_flint.patch
  ports/mosquitto/CONTROL
  ports/mosquitto/fix-dependence-pthreads.patch
  ports/mosquitto/portfile.cmake
  ports/pthreads/CMakeLists.txt
  ports/pthreads/CONTROL
  ports/pthreads/portfile.cmake
  ports/usbmuxd/CONTROL
  ports/usbmuxd/fix-dependence-pthreads.patch
  ports/usbmuxd/portfile.cmake
Labels: internal

#5388 RFC PR: Add DPDK package
  ports/dpdk/CMakeLists.txt
  ports/dpdk/CONTROL
  ports/dpdk/FindNuma.cmake
  ports/dpdk/dpdkConfig.cmake
  ports/dpdk/portfile.cmake
  ports/dpdk/usage
  scripts/cmake/vcpkg_execute_required_process.cmake
Labels: wip

#5598 [forest]update version.
  ports/forest/CONTROL
  ports/forest/portfile.cmake
Labels: internal

#5597 [coroutine]update source package hash.
  ports/coroutine/CONTROL
  ports/coroutine/portfile.cmake
Labels: internal

#5603 [tgui] Add gui-builder in tool feature
  ports/tgui/CONTROL
  ports/tgui/portfile.cmake
Labels: help wanted

#5608 [qt5-base] missing files in export/CI caching
  ports/qt5-base/configure_qt.cmake
  ports/qt5-base/portfile.cmake
Labels: internal

#5629 [libepoxy/fribidi] Update version of meson to support VS2019
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: internal

#5580 [apr]Enable option "APR_INSTALL_PRIVATE_H" to build non-standard files.
  ports/apr/CONTROL
  ports/apr/portfile.cmake
Labels: internal

#5647 [pangolin]Fix usage bug:include path has one more "../", add usage file.
  ports/pangolin/CONTROL
  ports/pangolin/fix-includepath-error.patch
  ports/pangolin/portfile.cmake
  ports/pangolin/usage
Labels: internal

#5645 [hunspell] update hunspell to 1.7.0
  ports/hunspell/CONTROL
  ports/hunspell/portfile.cmake
Labels: internal

#5641 [pixman]Update version to 0.38.0
  ports/pixman/CONTROL
  ports/pixman/portfile.cmake
Labels: internal

#5654 [ecm] Update ecm to 5.56.0
  ports/ecm/CONTROL
  ports/ecm/portfile.cmake
Labels: internal

#5653 [wangle]fix wangle-config.cmake bug
  ports/wangle/CONTROL
  ports/wangle/fix-config-cmake.patch
  ports/wangle/portfile.cmake
  ports/wangle/usage
Labels: internal

#5666 [libssh]fix config.cmake error, add usage.
  ports/libssh/CONTROL
  ports/libssh/fix-config-cmake.patch
  ports/libssh/portfile.cmake
  ports/libssh/usage
Labels: internal

#5665 [luasocket] Fix static build for renaming files
  ports/luasocket/CONTROL
  ports/luasocket/portfile.cmake
Labels: internal

#5643 [roaring] Add new port
  ports/roaring/CONTROL
  ports/roaring/portfile.cmake
Labels: wip

#5682 [curl]Add the dependency of the curl feature [ssh] to solve the lnk2019 error.
  ports/curl/CONTROL
Labels: internal

#5546 [capstone] Update Capstone to v4.0.1-49-ge3d5a594
  ports/capstone/CONTROL
  ports/capstone/portfile.cmake
Labels: wip

#5646 [cairo] Update version to 1.17.2
  ports/cairo/CONTROL
  ports/cairo/portfile.cmake
Labels: internal

#5696 [harfbuzz] Restore patches removed by #5359
  ports/harfbuzz/CONTROL
  ports/harfbuzz/find-package-freetype-2.patch
  ports/harfbuzz/glib-cmake.patch
  ports/harfbuzz/portfile.cmake
Labels: internal

#4661 [WIP][vtk] add the option -DModule_vtkGUISupportMFC=ON
  ports/vtk/CONTROL
  ports/vtk/portfile.cmake
Labels: wip

#3693 [rapidjson] Fix --head support
  ports/rapidjson/portfile.cmake
Labels: internal

#5745 [fribidi] Update Version to support static build
  ports/fribidi/CONTROL
  ports/fribidi/portfile.cmake
Labels: internal

#5749 [clapack]fix missing library and tools.
  ports/clapack/CONTROL
  ports/clapack/fix-lack-library.patch
  ports/clapack/portfile.cmake
Labels: internal

#5757 [ismrmrd] make optional hdf5 dependency explicit
  ports/ismrmrd/CONTROL
  ports/ismrmrd/optional_hdf5_dependency.patch
  ports/ismrmrd/portfile.cmake
Labels: internal

#5758 [liblemon][lemon] deprecate duplicate port, forward to original
  ports/lemon/CONTROL
  ports/lemon/portfile.cmake
  ports/lemon/remove-directory.patch
  ports/openmvg/CONTROL
Labels: internal

#5755 [draco]Fix build error on x86-uwp.
  ports/draco/CONTROL
  ports/draco/fix-compile-error-uwp.patch
  ports/draco/portfile.cmake
Labels: internal

#5744 [grpc] Update grpc to 1.9.1.
  ports/grpc/CONTROL
  ports/grpc/portfile.cmake
Labels: internal

#5799 [libnice]Fix build error in windows.
  ports/libnice/CONTROL
  ports/libnice/fix-build_in_windows.patch
  ports/libnice/portfile.cmake
Labels: internal

#5769 [apr-util]Fix static library usage bug.
  ports/apr-util/CONTROL
  ports/apr-util/portfile.cmake
Labels: internal

#5746 [nlohmann-json]update version to 3.6.0
  ports/nlohmann-json/CONTROL
  ports/nlohmann-json/portfile.cmake
Labels: internal

#5741 [openblas]Fix white-space-path configure bug.
  ports/openblas/CONTROL
  ports/openblas/fix-space-path.patch
  ports/openblas/portfile.cmake
Labels: internal

#5743 [libmikmod]fix missing dll bug.
  ports/libmikmod/CONTROL
  ports/libmikmod/fix-missing-dll.patch
  ports/libmikmod/portfile.cmake
Labels: internal

#5754 [SDL2_xxx]: Add CMake targets for SDL2 addons
  ports/freetype/portfile.cmake
  ports/sdl2-image/CMakeLists.txt
  ports/sdl2-image/CONTROL
  ports/sdl2-image/portfile.cmake
  ports/sdl2-mixer/CMakeLists.txt
  ports/sdl2-mixer/CONTROL
  ports/sdl2-mixer/portfile.cmake
  ports/sdl2-net/CMakeLists.txt
  ports/sdl2-net/CONTROL
  ports/sdl2-net/portfile.cmake
  ports/sdl2-ttf/CMakeLists.txt
  ports/sdl2-ttf/CONTROL
  ports/sdl2-ttf/portfile.cmake
Labels: help wanted

#5617 [capnproto] Add Capnproto package
  ports/capnproto/0001-fix-capnpc-extension-handling-on-Windows.patch
  ports/capnproto/CONTROL
  ports/capnproto/portfile.cmake
Labels: wip

#5835 [many ports]Add long path warnings
  ports/alembic/portfile.cmake
  ports/avro-c/portfile.cmake
  ports/aws-sdk-cpp/portfile.cmake
  ports/cgal/portfile.cmake
  ports/kinectsdk2/portfile.cmake
  ports/ompl/portfile.cmake
  ports/openmvg/portfile.cmake
  ports/xalan-c/portfile.cmake
Labels: internal

#5833 [mozjpeg]Fix installation files to the wrong directory
  ports/mozjpeg/CONTROL
  ports/mozjpeg/fix-install-error.patch
  ports/mozjpeg/portfile.cmake
Labels: internal

#5829 [jemalloc]Fix dll generated when generating static library
  ports/jemalloc/CONTROL
  ports/jemalloc/fix-static-build.patch
  ports/jemalloc/portfile.cmake
Labels: internal

#5827 [pcre2/caffe2] Fix space issue
  ports/caffe2/CONTROL
  ports/caffe2/fix-space.patch
  ports/caffe2/portfile.cmake
  ports/pcre2/CONTROL
  ports/pcre2/portfile.cmake
Labels: internal

#5650 Allow additional environment variables to be set in a clean environment
  docs/users/config-environment.md
  toolsrc/src/vcpkg/base/system.cpp
Labels: discussion needed

#5852 [decimal-for-cpp] update to 1.16
  ports/decimal-for-cpp/CONTROL
  ports/decimal-for-cpp/portfile.cmake
Labels: internal

#5578 [giflib]fix compile error in x64-uwp
  ports/giflib/CMakeLists.txt
  ports/giflib/fix-compile-error.patch
  ports/giflib/portfile.cmake
Labels: internal

#5454 [exiv2] Update exiv2 to 0.27 release, optionally support unicode on windows
  ports/exiv2/CONTROL
  ports/exiv2/iconv.patch
  ports/exiv2/portfile.cmake
  ports/exiv2/vcpkg-cmake-wrapper.cmake
Labels: wip

#5868 [signalrclient]Fix build error
  ports/signalrclient/0002_fix-compile-error.patch
  ports/signalrclient/CONTROL
  ports/signalrclient/portfile.cmake
Labels: internal

#5862 [jsonnet] Fix space path issue.
  ports/jsonnet/CONTROL
  ports/jsonnet/portfile.cmake
Labels: internal

#5863 [luajit]move luajit headers to the directory "include/luajit/" to avoid file conflicts.
  ports/luajit/CONTROL
  ports/luajit/portfile.cmake
Labels: internal

#5860 [abseil]Fix link error when using abseil library.
  ports/abseil/CONTROL
  ports/abseil/fix-usage-lnk-error.patch
  ports/abseil/portfile.cmake
Labels: internal

#5846 [pdal]fix missing vendor headers
  ports/pdal/0002-no-source-dir-writes.patch
  ports/pdal/0003-fix-copy-vendor.patch
  ports/pdal/CONTROL
  ports/pdal/portfile.cmake
Labels: internal

#5628 [libharu]fix build failure.
  ports/libharu/CONTROL
  ports/libharu/fix-build-fail.patch
  ports/libharu/portfile.cmake
Labels: internal
