Repository microsoft/vcpkg, pull requests merged in 2019-09, with the labels that each got.

#7938 [breakpad] Fix build failed with Visual Studio 2019
  ports/breakpad/CONTROL
  ports/breakpad/fix-unique_ptr.patch
  ports/breakpad/portfile.cmake
Labels: internal

#7887 [gtest]Re-fix gmock target.
  ports/gtest/CONTROL
  ports/gtest/fix-gmock-cmake.patch
  ports/gtest/portfile.cmake
  ports/gtest/usage
Labels: internal

#7451 [libxslt]Fix dependent ports in static builds.
  ports/libxslt/0002-Fix-lzma.patch
  ports/libxslt/CONTROL
  ports/libxslt/portfile.cmake
Labels: internal

#7549 [dmlc] Add new port
  ports/dmlc/CONTROL
  ports/dmlc/portfile.cmake
Labels: internal

#7848 [raylib] update to 2.5.0
  ports/raylib/CONTROL
  ports/raylib/portfile.cmake
Labels: internal

#7987 [cppkafka] Add new port
  ports/cppkafka/CONTROL
  ports/cppkafka/portfile.cmake
Labels: internal

#7990 [gettext]Improve gettext on Linux.
  ports/gettext/CONTROL
  ports/gettext/portfile.cmake
Labels: internal

#7986 modernize many ports
  ports/aixlog/CONTROL
  ports/aixlog/portfile.cmake
  ports/chaiscript/CONTROL
  ports/chaiscript/portfile.cmake
  ports/dlfcn-win32/CONTROL
  ports/dlfcn-win32/portfile.cmake
  ports/enet/CONTROL
  ports/enet/portfile.cmake
  ports/fltk/CONTROL
  ports/fltk/portfile.cmake
  ports/fmi4cpp/CONTROL
  ports/fmi4cpp/portfile.cmake
  ports/fmilib/CONTROL
  ports/fmilib/portfile.cmake
  ports/freetds/CONTROL
  ports/freetds/portfile.cmake
  ports/gainput/CONTROL
  ports/gainput/portfile.cmake
  ports/geographiclib/CONTROL
  ports/geographiclib/portfile.cmake
  ports/glog/CONTROL
  ports/glog/portfile.cmake
  ports/irrlicht/CONTROL
  ports/irrlicht/LICENSE.txt
  ports/irrlicht/portfile.cmake
  ports/libmikmod/CONTROL
  ports/libmikmod/portfile.cmake
  ports/libodb-mysql/CONTROL
  ports/libodb-mysql/portfile.cmake
  ports/libodb-sqlite/CONTROL
  ports/libodb-sqlite/portfile.cmake
  ports/libodb/CONTROL
  ports/libodb/portfile.cmake
  ports/libsquish/CONTROL
  ports/libsquish/portfile.cmake
  ports/libxslt/CONTROL
  ports/libxslt/portfile.cmake
  ports/lzo/CONTROL
  ports/lzo/portfile.cmake
  ports/nanovg/CONTROL
  ports/nanovg/portfile.cmake
  ports/ode/CONTROL
  ports/ode/portfile.cmake
  ports/opencsg/CONTROL
  ports/opencsg/portfile.cmake
  ports/orocos-kdl/CONTROL
  ports/orocos-kdl/portfile.cmake
  ports/pangomm/CONTROL
  ports/pangomm/portfile.cmake
  ports/pcre/CONTROL
  ports/pcre/portfile.cmake
  ports/qt5-gamepad/CONTROL
  ports/wavpack/CONTROL
  ports/wavpack/portfile.cmake
Labels: internal

#7377 [x-history] Prints CONTROL version history of a port 👻
  toolsrc/include/vcpkg/commands.h
  toolsrc/src/vcpkg/commands.cpp
  toolsrc/src/vcpkg/commands.porthistory.cpp
  toolsrc/src/vcpkg/help.cpp
  toolsrc/vcpkglib/vcpkglib.vcxproj
  toolsrc/vcpkglib/vcpkglib.vcxproj.filters
Labels: internal, vcpkg feature, wip

#8023 [tensorflow-cc]Fix build error and add warning message.
  ports/tensorflow-cc/CONTROL
  ports/tensorflow-cc/fix-build-error.patch
  ports/tensorflow-cc/portfile.cmake
Labels: internal, wip

#8048 Add August changelog
  CHANGELOG.md
Labels: internal

#7795 [xalan-c] fixed cmake files location
  ports/xalan-c/CONTROL
  ports/xalan-c/portfile.cmake
Labels: discussion needed

#8101 fix x-history help desc.
  toolsrc/src/vcpkg/help.cpp
Labels: internal

#8024 [dimcli] Upgrade to version 5.0.1
  ports/dimcli/CONTROL
  ports/dimcli/fix-NameBoolean.patch
  ports/dimcli/portfile.cmake
Labels: internal

#8039 [parallelstl] Add new port
  ports/parallelstl/CONTROL
  ports/parallelstl/fix-install-header.patch
  ports/parallelstl/portfile.cmake
Labels: internal

#8018 [tbb]Fix static build.
  ports/tbb/CONTROL
  ports/tbb/fix-static-build.patch
  ports/tbb/portfile.cmake
Labels: internal

#8070 [sdl1]Support linux build.
  ports/sdl1/CONTROL
  ports/sdl1/fix-linux-build.patch
  ports/sdl1/portfile.cmake
Labels: internal

#8135 [vcpkg] Fix `depend-info` command arguments arity
  toolsrc/src/vcpkg/commands.dependinfo.cpp
Labels: internal

#8051 [glslang]Fix generated cmake files.
  ports/glslang/CONTROL
  ports/glslang/portfile.cmake
Labels: internal

#7720 [sdl2-mixer]Remove useless dependency link libraries.
  ports/sdl2-mixer/CMakeLists.txt
  ports/sdl2-mixer/CONTROL
  ports/sdl2-mixer/portfile.cmake
Labels: internal

#8139 [otl] fix hash and update version
  ports/otl/CONTROL
  ports/otl/portfile.cmake
Labels: internal

#8125 [grppi] Add new port
  ports/grppi/CONTROL
  ports/grppi/fix-build-error.patch
  ports/grppi/fix-support-other-compilers.patch
  ports/grppi/portfile.cmake
Labels: internal

#8115 [geographiclib]Fix usage error and cmake path in Linux.
  ports/geographiclib/CONTROL
  ports/geographiclib/fix-usage.patch
  ports/geographiclib/portfile.cmake
  ports/geographiclib/usage
Labels: internal

#8194 [yara] Update to 3.10.0
  ports/yara/CMakeLists.txt
  ports/yara/CONTROL
  ports/yara/portfile.cmake
Labels: internal

#8042 [rabit] Fix file conflict with dmlc
  ports/rabit/CONTROL
  ports/rabit/fix-file-conflict.patch
  ports/rabit/portfile.cmake
Labels: internal

#7852 [gdcm] Fix file UseGDCM.cmake path name
  ports/gdcm/CONTROL
  ports/gdcm/Fix-Cmake_DIR.patch
  ports/gdcm/portfile.cmake
Labels: internal

#8188 [cpputest] Add new port
  ports/cpputest/CONTROL
  ports/cpputest/fix-arm-build-error.patch
  ports/cpputest/portfile.cmake
Labels: internal

#8191 [clapack] Fix clapack-targets.cmake path in clpack-config.cmake
  ports/clapack/CONTROL
  ports/clapack/fix-ConfigFile.patch
  ports/clapack/portfile.cmake
Labels: internal

#8192 [embree3]Fix static build and cmake path.
  ports/embree3/CONTROL
  ports/embree3/fix-cmake-path.patch
  ports/embree3/portfile.cmake
Labels: internal

#7988 [glib]Fix missing dependency selinux.
  ports/glib/CMakeLists.txt
  ports/glib/CONTROL
  ports/glib/portfile.cmake
Labels: internal

#7919 [llvm]Fix build error on Linux: cannot find -lxml2.
  ports/llvm/CONTROL
  ports/llvm/fix-linux-build.patch
  ports/llvm/portfile.cmake
Labels: internal

#7955 [zfp] Add new port
  ports/zfp/CONTROL
  ports/zfp/fix-build-error.patch
  ports/zfp/fix-install-tools.patch
  ports/zfp/portfile.cmake
Labels: internal

#8202 [dcmtk] Fix build error on Linux
  ports/dcmtk/CONTROL
  ports/dcmtk/portfile.cmake
Labels: internal

#8210 [openimageio] Add opencolorio as feature
  ports/openimageio/CONTROL
  ports/openimageio/portfile.cmake
Labels: internal

#8206 [rabit] Fix cmake files path
  ports/rabit/CONTROL
  ports/rabit/portfile.cmake
Labels: internal

#8129 [vcpkg] Continue on malformed paths in PATH
  toolsrc/src/vcpkg/base/files.cpp
Labels: internal

#8207 [jinja2cpplight] Add new port
  ports/jinja2cpplight/CONTROL
  ports/jinja2cpplight/portfile.cmake
Labels: internal

#7985 [libepoxy]Add support with unix.
  ports/libepoxy/CONTROL
  ports/libepoxy/portfile.cmake
Labels: internal

#7991 [atk]Support UNIX.
  ports/atk/CMakeLists.txt
  ports/atk/CONTROL
  ports/atk/fix-encoding.patch
  ports/atk/fix-linux-config.patch
  ports/atk/portfile.cmake
Labels: internal

#8144 [duktape] Change download path of pip.
  ports/duktape/CONTROL
  ports/duktape/portfile.cmake
Labels: internal

#8232 [cgicc]Fix linux build.
  ports/cgicc/CMakeLists.txt
  ports/cgicc/CONTROL
  ports/cgicc/fix-define.patch
  ports/cgicc/portfile.cmake
Labels: internal

#8230 [openimageio]Re-fix find openexr issue.
  ports/openimageio/CONTROL
  ports/openimageio/fix_find_openexr.patch
Labels: internal

#8245 [simpleini cpp-redis tacopie] ports update
  ports/cpp-redis/CONTROL
  ports/cpp-redis/portfile.cmake
  ports/simpleini/CONTROL
  ports/simpleini/portfile.cmake
  ports/tacopie/CONTROL
  ports/tacopie/portfile.cmake
Labels: internal

#8249 [cairo]Add feature X11.
  ports/cairo/CMakeLists.txt
  ports/cairo/CONTROL
  ports/cairo/portfile.cmake
Labels: internal

#8266 [foonathan-memory] Fix using vcpkg_check_features error
  ports/foonathan-memory/CONTROL
  ports/foonathan-memory/portfile.cmake
Labels: internal

#8251 [io2d]Fix linux build: add dependency cairo[x11].
  ports/io2d/CONTROL
  ports/io2d/fix-linux-build.patch
  ports/io2d/portfile.cmake
Labels: internal

#8276 [linenoise-ng] Fix flaky config
  ports/linenoise-ng/CONTROL
  ports/linenoise-ng/portfile.cmake
Labels: internal

#8299 [armadillo] Fix configure_file failed
  ports/armadillo/CONTROL
  ports/armadillo/portfile.cmake
Labels: internal

#8303 [realsense2] fix dependency glfw3 and mismatching number of debug and release binaries
  ports/realsense2/CONTROL
  ports/realsense2/fix-dependency-glfw3.patch
  ports/realsense2/portfile.cmake
Labels: internal

#8252 [open62541] fix dynamic build
  ports/open62541/CONTROL
  ports/open62541/portfile.cmake
Labels: internal

#8208 [sdl2-mixer] Fix features dependency link.
  ports/sdl2-mixer/CMakeLists.txt
  ports/sdl2-mixer/CONTROL
  ports/sdl2-mixer/portfile.cmake
Labels: internal

#8308 [chartdir] fix hash for osx
  ports/chartdir/CONTROL
  ports/chartdir/portfile.cmake
Labels: internal

#8317 [asynch]Add new port.
  ports/asynch/CONTROL
  ports/asynch/portfile.cmake
Labels: internal

#8319 [minimp3] Add new port
  ports/minimp3/CONTROL
  ports/minimp3/portfile.cmake
Labels: internal

#8326 [proj4] Allow consumers to use a different MSVC version from the one used to compile proj4
  ports/proj4/0004-CMake-skip-msvc-check.patch
  ports/proj4/portfile.cmake
Labels: internal

#8312 [libiconv] Guard imported targets in non-Windows
  ports/libiconv/CONTROL
  ports/libiconv/unofficial-iconv-config.cmake
Labels: internal

#8335 [sdl2-mixer]Re-fix dynamic call.
  ports/sdl2-mixer/CMakeLists.txt
  ports/sdl2-mixer/CONTROL
Labels: internal

#8327 [sdl1] fix windows sdk 18362 build failure
  ports/sdl1/CONTROL
  ports/sdl1/SDL_dynamic.vcxproj
  ports/sdl1/SDL_static.vcxproj
Labels: internal

#8261 [libosip2]Add new port.
  ports/libosip2/CONTROL
  ports/libosip2/portfile.cmake
Labels: internal

#8263 [arrow]Fix build error on Visual Studio 2019.
  ports/arrow/CONTROL
  ports/arrow/fix-msvc-1900.patch
  ports/arrow/portfile.cmake
Labels: internal

#8243 [sol2]Disable export namespace to fix usage issue.
  ports/sol2/CONTROL
  ports/sol2/fix-namespace.patch
  ports/sol2/portfile.cmake
Labels: internal

#8345 [vtk] Fix vtk[python] build failure
  ports/vtk/CONTROL
  ports/vtk/portfile.cmake
Labels: internal

#8342 [CI system] Add features to test result xml
  toolsrc/src/vcpkg/commands.ci.cpp
Labels: internal

#8331 [many ports] Warning to VCPKG long build path
  ports/alembic/CONTROL
  ports/alembic/portfile.cmake
  ports/avro-c/CONTROL
  ports/avro-c/portfile.cmake
  ports/aws-sdk-cpp/CONTROL
  ports/aws-sdk-cpp/portfile.cmake
  ports/boost-system/CONTROL
  ports/boost-system/portfile.cmake
  ports/cgal/CONTROL
  ports/cgal/portfile.cmake
  ports/eigen3/CONTROL
  ports/eigen3/portfile.cmake
  ports/itk/CONTROL
  ports/itk/portfile.cmake
  ports/kinectsdk2/CONTROL
  ports/kinectsdk2/portfile.cmake
  ports/ompl/CONTROL
  ports/ompl/portfile.cmake
  ports/openmvg/CONTROL
  ports/openmvg/portfile.cmake
Labels: internal

#8302 [nanogui] Add new port
  ports/nanogui/CONTROL
  ports/nanogui/fix-cmakelists.patch
  ports/nanogui/portfile.cmake
  ports/nanovg/CMakeLists.txt
  ports/nanovg/CONTROL
Labels: internal

#8102 [halide]Upgrade to release_2019_08_27.
  ports/halide/CONTROL
  ports/halide/fix-install-path.patch
  ports/halide/portfile.cmake
  ports/llvm/CONTROL
  ports/llvm/portfile.cmake
Labels: internal

#8355 [librdkafka] Add vcpkg-cmake-wrapper.cmake
  ports/librdkafka/CONTROL
  ports/librdkafka/vcpkg-cmake-wrapper.cmake
Labels: internal

#8073 [cppkafka] Fix dynamic build.
  ports/cppkafka/CONTROL
  ports/cppkafka/fix-dynamic.patch
  ports/cppkafka/portfile.cmake
Labels: internal

#8259 [hpx] Redirect --head to `stable`
  ports/hpx/CONTROL
  ports/hpx/portfile.cmake
Labels: internal

#8370 [assimp] Update the version to 5.0.0
  ports/assimp/dont-overwrite-prefix-path.patch
  ports/assimp/fix-static-build-error.patch
  ports/assimp/portfile.cmake
  ports/assimp/remove-useless-path.patch
  ports/assimp/uninitialized-variable.patch
Labels: internal

#8371 [asynch,minimp3]Change copyright path and name.
  ports/asynch/CONTROL
  ports/asynch/portfile.cmake
  ports/minimp3/CONTROL
  ports/minimp3/portfile.cmake
  ports/winreg/CONTROL
  ports/winreg/portfile.cmake
Labels: internal

#7329 [angle] Update to the latest commit.
  ports/angle/001-fix-uwp.patch
  ports/angle/002-fix-linux.patch
  ports/angle/CMakeLists.txt
  ports/angle/CONTROL
  ports/angle/portfile.cmake
Labels: internal

#8381 [assimp] Update the version
  ports/assimp/CONTROL
Labels: internal
