Repository microsoft/vcpkg, pull requests merged in 2019-11, with the labels that each got.

#8853 Add October changelog
  CHANGELOG.md
Labels: internal

#8848 [jsonnet]Upgrade to 0.14.0.
  ports/jsonnet/001-enable-msvc.patch
  ports/jsonnet/002-fix-dependency-and-install.patch
  ports/jsonnet/CONTROL
  ports/jsonnet/portfile.cmake
Labels: internal

#8843 [hiredis] Add new port
  ports/hiredis/CONTROL
  ports/hiredis/portfile.cmake
Labels: internal

#8623 [opencv3] Upgrade to version 3.4.8
  ports/opencv3/0001-disable-downloading.patch
  ports/opencv3/0002-install-options.patch
  ports/opencv3/0009-fix-uwp.patch
  ports/opencv3/CONTROL
  ports/opencv3/portfile.cmake
Labels: internal

#8894 Update README.md
  README.md
Labels: internal

#9008 [soci] Upgrade to version 4.0.0
  ports/soci/0001-Deduce-reference-in-boost-fusion-for_each.patch
  ports/soci/0002-Find-PostgreSQL-debug-library.patch
  ports/soci/CONTROL
  ports/soci/portfile.cmake
Labels: internal

#8980 [orc]Upgrade to 1.5.7, disable tzdata test.
  ports/orc/0005-disable-tzdata.patch
  ports/orc/CONTROL
  ports/orc/no-werror.patch
  ports/orc/portfile.cmake
Labels: internal

#8979 [openvdb]Upgrade to 6.2.1
  ports/openvdb/0002-fix-cmake-modules.patch
  ports/openvdb/0003-fix-cmake.patch
  ports/openvdb/CONTROL
  ports/openvdb/portfile.cmake
Labels: internal

#8844 [botan]Upgrade to 2.12.1
  ports/botan/CONTROL
  ports/botan/fix-generate-build-path.patch
  ports/botan/portfile.cmake
Labels: internal

#8790 [libbson][mongo-c-driver] Update to 1.15.1. Parse CONTROL file for version number
  ports/libbson/CONTROL
  ports/libbson/portfile.cmake
  ports/mongo-c-driver/CONTROL
  ports/mongo-c-driver/portfile.cmake
Labels: internal

#8652 [libpopt]Fix linux build.
  ports/libpopt/CMakeLists.txt
  ports/libpopt/CONTROL
Labels: internal

#8622 [lipng/libpng-apng]Remove port libpng-apng and add apng as a feature with libpng.
  ports/libpng-apng/CONTROL
  ports/libpng-apng/portfile.cmake
  ports/libpng-apng/usage
  ports/libpng-apng/use-abort-on-all-platforms.patch
  ports/libpng-apng/vcpkg-cmake-wrapper.cmake
  ports/libpng/CONTROL
  ports/libpng/portfile.cmake
  ports/libpng/skip-install-symlink.patch
Labels: internal

#8349 [libevent] add features
  ports/evpp/CONTROL
  ports/libevent/CONTROL
  ports/libevent/portfile.cmake
Labels: internal

#8992 [freetype-gl] Fix POST_BUILD_CHECKS_FAILED failure on Unix
  ports/freetype-gl/CONTROL
  ports/freetype-gl/portfile.cmake
Labels: internal

#8918 [libzip] Fix patch not applying
  ports/libzip/CONTROL
  ports/libzip/avoid_computation_on_void_pointer.patch
  ports/libzip/portfile.cmake
Labels: internal

#8877 [tgui]Update to 0.8.6
  ports/tgui/CONTROL
  ports/tgui/portfile.cmake
Labels: internal

#9007 [magic-enum] Fix export config.cmake issue
  ports/magic-enum/CONTROL
  ports/magic-enum/portfile.cmake
Labels: internal

#8937 [otl] Upgrade to version 4.0.448
  ports/otl/CONTROL
  ports/otl/portfile.cmake
Labels: internal

#8901 [stlab] Update to 1.5.1
  ports/stlab/CONTROL
  ports/stlab/dont-require-testing.patch
  ports/stlab/portfile.cmake
Labels: internal

#8846 [redis-plus-plus] Add new port
  ports/redis-plus-plus/CONTROL
  ports/redis-plus-plus/disable-build-test.patch
  ports/redis-plus-plus/portfile.cmake
Labels: internal

#8765 [folly/fizz]Upgrade version.
  ports/fizz/CONTROL
  ports/fizz/portfile.cmake
  ports/folly/CONTROL
  ports/folly/boost-1.70.patch
  ports/folly/portfile.cmake
Labels: internal

#9069 [nlohmann-json] Upgrade to 3.7.3
  ports/nlohmann-json/CONTROL
  ports/nlohmann-json/portfile.cmake
Labels: internal

#8978 [netcdf-cxx4] Update to 4.3.1
  ports/netcdf-cxx4/CONTROL
  ports/netcdf-cxx4/fix-dependecy-hdf5.patch
  ports/netcdf-cxx4/install-destination.patch
  ports/netcdf-cxx4/portfile.cmake
Labels: internal

#8962 [nanoflann] Add new port
  ports/nanoflann/CONTROL
  ports/nanoflann/portfile.cmake
Labels: internal

#6891 [feature] add `vcpkg export --x-chocolatey` support
  toolsrc/include/vcpkg/export.chocolatey.h
  toolsrc/src/vcpkg/export.chocolatey.cpp
  toolsrc/src/vcpkg/export.cpp
  toolsrc/vcpkglib/vcpkglib.vcxproj
  toolsrc/vcpkglib/vcpkglib.vcxproj.filters
Labels: vcpkg feature

#8944 [portaudio] Fix library cannot be found
  ports/portaudio/CONTROL
  ports/portaudio/fix-include.patch
  ports/portaudio/fix-library-can-not-be-found.patch
  ports/portaudio/portfile.cmake
Labels: internal

#8903 [wt] Update to 4.1.1
  ports/wt/0003-disable-boost-autolink.patch
  ports/wt/0004-link-ssl.patch
  ports/wt/CONTROL
  ports/wt/portfile.cmake
Labels: internal

#8648 [pfring]Add new port.
  ports/pfring/CONTROL
  ports/pfring/portfile.cmake
Labels: internal

#8899 [z3] Update to 4.8.6
  ports/z3/CONTROL
  ports/z3/fix-install-path.patch
  ports/z3/portfile.cmake
Labels: internal

#9042 [pdcurses] Fix linkage error
  ports/pdcurses/CONTROL
  ports/pdcurses/portfile.cmake
Labels: internal

#5719 [vcpkg_from_github] Allow targeting Github Enterprise instances
  docs/maintainers/vcpkg_from_github.md
  scripts/cmake/vcpkg_from_github.cmake
Labels: discussion needed

#8785 [angle] Add option /bigobj to compiler
  ports/angle/CMakeLists.txt
  ports/angle/CONTROL
Labels: internal

#8779 [spdlog]Update to 1.4.2
  ports/spdlog/CONTROL
  ports/spdlog/disable-master-project-check.patch
  ports/spdlog/fix-error-4275.patch
  ports/spdlog/fix-feature-export.patch
  ports/spdlog/fix-uwp.patch
  ports/spdlog/portfile.cmake
Labels: internal

#9075 [minizip, assimp] Export minizip CMake targets; Add minizip as assimp dependency
  ports/assimp/CONTROL
  ports/assimp/fix_minizip.patch
  ports/assimp/portfile.cmake
  ports/minizip/CMakeLists.txt
  ports/minizip/CONTROL
  ports/minizip/minizipConfig.cmake.in
  ports/minizip/portfile.cmake
Labels: internal

#8931 [libmodman, libproxy] Add new ports
  ports/libmodman/CONTROL
  ports/libmodman/fix-install-path.patch
  ports/libmodman/fix-undefined-typeid.patch
  ports/libmodman/portfile.cmake
  ports/libmodman/usage
  ports/libmodman/vcpkg-cmake-wrapper.cmake
  ports/libproxy/CONTROL
  ports/libproxy/fix-arm-build.patch
  ports/libproxy/fix-dependency-libmodman.patch
  ports/libproxy/fix-install-py.patch
  ports/libproxy/fix-tools-path.patch
  ports/libproxy/portfile.cmake
  ports/libproxy/support-windows.patch
  ports/libproxy/usage
  ports/libproxy/vcpkg-cmake-wrapper.cmake
Labels: internal
