Repository microsoft/vcpkg, pull requests merged in 2019-08, with the labels that each got.

#7413 [pcl]Fix Build failure in linux
  ports/pcl/CONTROL
  ports/pcl/boost-1.70.patch
  ports/pcl/portfile.cmake
Labels: internal

#7501 Add July changelog
  CHANGELOG.md
Labels: internal

#7496 [xalan-c] Bump version number
  ports/xalan-c/CONTROL
Labels: internal

#7487 [easyhook]Add new port.
  ports/easyhook/CONTROL
  ports/easyhook/fix-build.patch
  ports/easyhook/portfile.cmake
Labels: internal

#7484 [manyports]Regenerate patches and modify how the patches are used.
  ports/ccfits/CONTROL
  ports/ccfits/dll_exports.patch
  ports/ccfits/portfile.cmake
  ports/itpp/CONTROL
  ports/itpp/fix-linux.patch
  ports/itpp/fix-uwp.patch
  ports/itpp/portfile.cmake
  ports/mpg123/CONTROL
  ports/mpg123/portfile.cmake
  ports/qwt/CONTROL
  ports/qwt/build-static-lib.patch
  ports/qwt/fix-dynamic-static.patch
  ports/qwt/portfile.cmake
  ports/sdl1/CONTROL
  ports/sdl1/SDL_dynamic.vcxproj
  ports/sdl1/SDL_static.vcxproj
  ports/sdl1/SDLmain_dynamic.vcxproj
  ports/sdl1/SDLmain_static.vcxproj
  ports/sdl1/portfile.cmake
  ports/sdl1/static-build.patch
Labels: internal

#7520 [gdal] Fix duplicate pdb file
  ports/gdal/CONTROL
  ports/gdal/portfile.cmake
Labels: internal

#7518 [brigand] Add new port
  ports/brigand/CONTROL
  ports/brigand/fix-install-targets.patch
  ports/brigand/portfile.cmake
Labels: internal

#7512 [ctbignum] Add new port
  ports/ctbignum/CONTROL
  ports/ctbignum/portfile.cmake
Labels: internal

#7527 [argh] fix flaky cmake config
  ports/argh/CONTROL
  ports/argh/portfile.cmake
Labels: internal

#7465 [libusb]Fix using mismatched CRT_linkage/library_linkage issue.
  ports/libusb/CONTROL
  ports/libusb/portfile.cmake
Labels: internal

#7502 [vcpkg-docs] Reword and reorganize overlay-triplets-linux-dynamic.md
  docs/examples/overlay-triplets-linux-dynamic.md
Labels: internal

#7508 improve logic expression evaluation
  ports/pango/CONTROL
  toolsrc/include/vcpkg/binaryparagraph.h
  toolsrc/include/vcpkg/logicexpression.h
  toolsrc/include/vcpkg/paragraphs.h
  toolsrc/include/vcpkg/statusparagraph.h
  toolsrc/src/vcpkg/binaryparagraph.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.cache.cpp
  toolsrc/src/vcpkg/commands.import.cpp
  toolsrc/src/vcpkg/logicexpression.cpp
  toolsrc/src/vcpkg/paragraphs.cpp
  toolsrc/src/vcpkg/parse.cpp
  toolsrc/src/vcpkg/sourceparagraph.cpp
  toolsrc/src/vcpkg/statusparagraph.cpp
  toolsrc/src/vcpkg/userconfig.cpp
  toolsrc/vcpkg.sln
  toolsrc/vcpkglib/vcpkglib.vcxproj
  toolsrc/vcpkglib/vcpkglib.vcxproj.filters
Labels: internal

#7476 [ffmpeg]Fix debug build in Windows.
  ports/ffmpeg/CONTROL
  ports/ffmpeg/fix-debug-build.patch
  ports/ffmpeg/portfile.cmake
Labels: internal

#7570 [vcpkg] Make RealFilesystem::remove_all much, much faster, and start benchmarking
  .gitignore
  toolsrc/CMakeLists.txt
  toolsrc/include/pch.h
  toolsrc/include/vcpkg-test/util.h
  toolsrc/include/vcpkg/base/files.h
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/include/vcpkg/base/util.h
  toolsrc/include/vcpkg/base/work_queue.h
  toolsrc/include/vcpkg/binaryparagraph.h
  toolsrc/include/vcpkg/build.h
  toolsrc/include/vcpkg/dependencies.h
  toolsrc/include/vcpkg/logicexpression.h
  toolsrc/include/vcpkg/pragmas.h
  toolsrc/include/vcpkg/sourceparagraph.h
  toolsrc/include/vcpkg/vcpkgpaths.h
  toolsrc/src/vcpkg-test/files.cpp
  toolsrc/src/vcpkg-test/util.cpp
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/base/files.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.ci.cpp
  toolsrc/src/vcpkg/commands.dependinfo.cpp
  toolsrc/src/vcpkg/commands.search.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/install.cpp
  toolsrc/src/vcpkg/logicexpression.cpp
  toolsrc/src/vcpkg/paragraphs.cpp
  toolsrc/src/vcpkg/parse.cpp
  toolsrc/src/vcpkg/remove.cpp
  toolsrc/src/vcpkg/sourceparagraph.cpp
  toolsrc/src/vcpkg/userconfig.cpp
  toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
  toolsrc/src/vcpkg/vcpkgpaths.cpp
Labels: internal

#7419 [openimageio] Fix feature libraw build errors
  ports/openimageio/CONTROL
  ports/openimageio/portfile.cmake
  ports/openimageio/remove_wrong_dependency.patch
Labels: internal

#7464 [pdqsort] Add new port
  ports/pdqsort/CONTROL
  ports/pdqsort/portfile.cmake
Labels: internal

#7588 [openimageio] find_package support
  ports/openimageio/CONTROL
  ports/openimageio/portfile.cmake
  ports/openimageio/vcpkg-cmake-wrapper.cmake
Labels: internal

#7587 [vcpkg] Revert accidental removal of powershell-core usage in bb3a9ddb6ec917f54
  ports/jsonnet/CONTROL
  ports/jsonnet/portfile.cmake
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/tools.cpp
Labels: internal

#7561 [duckx] Add new port
  ports/duckx/CONTROL
  ports/duckx/portfile.cmake
Labels: internal

#7452 [rocksdb]Change linkage type to static.
  ports/rocksdb/CONTROL
  ports/rocksdb/portfile.cmake
Labels: internal

#7595 [bento4] Add new port
  ports/bento4/CONTROL
  ports/bento4/LICENSE
  ports/bento4/fix-install-and-c4996-error.patch
  ports/bento4/portfile.cmake
Labels: internal

#7552 [dbow2] Add new port
  ports/dbow2/CONTROL
  ports/dbow2/portfile.cmake
Labels: internal

#7637 [vcpkg] Fix the build on VS2015 debug
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/src/vcpkg/install.cpp
Labels: internal

#7623 vs 2019 integration bug
  scripts/buildsystems/vcpkg.cmake
Labels: internal

#7622 [tiff][tesseract][xerces-c] Disable unmanaged optional dependencies
  ports/tesseract/CONTROL
  ports/tesseract/portfile.cmake
  ports/tiff/CONTROL
  ports/tiff/portfile.cmake
  ports/xerces-c/CONTROL
  ports/xerces-c/portfile.cmake
Labels: internal

#7478 [yasm] Add new port
  ports/yasm/CONTROL
  ports/yasm/portfile.cmake
Labels: internal

#7662 [usockets] upgrade to v0.3.1
  ports/usockets/CONTROL
  ports/usockets/portfile.cmake
Labels: internal

#7651 [dimcli] Fix build error C2220
  ports/dimcli/CONTROL
  ports/dimcli/fix-NameBoolean.patch
  ports/dimcli/portfile.cmake
Labels: internal

#7558 [vcpkg_check_features] Set output variable explicitly and allow reverse-logic check
  docs/maintainers/portfile-functions.md
  docs/maintainers/vcpkg_check_features.md
  docs/maintainers/vcpkg_configure_cmake.md
  docs/maintainers/vcpkg_prettify_command.md
  ports/czmq/CONTROL
  ports/czmq/portfile.cmake
  ports/darknet/CONTROL
  ports/darknet/portfile.cmake
  ports/librdkafka/portfile.cmake
  ports/mimalloc/CONTROL
  ports/mimalloc/portfile.cmake
  ports/mongo-c-driver/CONTROL
  ports/mongo-c-driver/portfile.cmake
  ports/oniguruma/CONTROL
  ports/oniguruma/portfile.cmake
  ports/opencv/CONTROL
  ports/opencv4/CONTROL
  ports/opencv4/portfile.cmake
  ports/paho-mqttpp3/CONTROL
  ports/paho-mqttpp3/portfile.cmake
  ports/pcl/CONTROL
  ports/pcl/portfile.cmake
  ports/rocksdb/portfile.cmake
  ports/xsimd/CONTROL
  ports/xsimd/portfile.cmake
  ports/xtensor/CONTROL
  ports/xtensor/portfile.cmake
  ports/zeromq/CONTROL
  ports/zeromq/portfile.cmake
  scripts/cmake/vcpkg_check_features.cmake
  scripts/cmake/vcpkg_configure_cmake.cmake
Labels: internal, vcpkg feature, wip

#7608 [ffmpeg]Add feature avresample.
  ports/ffmpeg/CONTROL
  ports/ffmpeg/portfile.cmake
Labels: internal

#7643 [depend-info] Fix bugs, add `--sort`, `--show-depth` and `--max-recurse` options
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/include/vcpkg/commands.h
  toolsrc/src/vcpkg/commands.cpp
  toolsrc/src/vcpkg/commands.dependinfo.cpp
Labels: internal, vcpkg feature, wip

#7698 [poco]Upgrade version to 1.9.2 release.
  ports/poco/CONTROL
  ports/poco/find_pcre.patch
  ports/poco/fix_foundation_link.patch
  ports/poco/include_pcre.patch
  ports/poco/portfile.cmake
  ports/poco/static_pcre.patch
  ports/poco/unbundled_pdf.patch
Labels: internal

#7670 [spdlog] fix cmake targets path
  ports/spdlog/CONTROL
  ports/spdlog/portfile.cmake
Labels: internal

#7669 [libgit2] Upgrade to version 0.28.3
  ports/libgit2/CONTROL
  ports/libgit2/portfile.cmake
Labels: internal

#7699 [nghttp2] Upgrade to version 1.39.2
  ports/nghttp2/CONTROL
  ports/nghttp2/enable-static.patch
  ports/nghttp2/portfile.cmake
Labels: internal

#7700 [czmq/pcl]Fix judgment feature condition.
  ports/czmq/CONTROL
  ports/czmq/portfile.cmake
  ports/pcl/CONTROL
  ports/pcl/portfile.cmake
Labels: internal

#7547 [pistache] Add new port
  ports/pistache/CONTROL
  ports/pistache/portfile.cmake
Labels: internal

#7516 [hfsm2] Add new port
  ports/hfsm2/CONTROL
  ports/hfsm2/portfile.cmake
Labels: internal

#7358 [leptonica] Upgrade to 1.78.0
  ports/leptonica/CONTROL
  ports/leptonica/portfile.cmake
  ports/leptonica/use-tiff-libraries.patch
Labels: internal

#7697 [geographiclib] Fix build error on Linux
  ports/geographiclib/CONTROL
  ports/geographiclib/portfile.cmake
Labels: internal

#7710 [libmariadb]Fix usage error LNK2001.
  ports/libmariadb/CONTROL
  ports/libmariadb/fix-InstallPath.patch
  ports/libmariadb/portfile.cmake
Labels: internal

#7594 [field3d] Add new port
  ports/field3d/CONTROL
  ports/field3d/fix-build_error.patch
  ports/field3d/portfile.cmake
Labels: internal

#7305 [vcpkg] Public ABI override option
  scripts/get_triplet_environment.cmake
  scripts/ports.cmake
  toolsrc/VERSION.txt
  toolsrc/include/vcpkg/binaryparagraph.h
  toolsrc/include/vcpkg/build.h
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/sourceparagraph.cpp
Labels: internal

#7548 [open62541, duktape] Update hash for pip.
  ports/duktape/CMakeLists.txt
  ports/duktape/CONTROL
  ports/duktape/portfile.cmake
Labels: internal

#7638 [vcpkg] Make CMakelists nicer 😁
  scripts/bootstrap.sh
  toolsrc/CMakeLists.txt
  toolsrc/include/catch2/catch.hpp
  toolsrc/include/vcpkg-test/util.h
  toolsrc/include/vcpkg/base/chrono.h
  toolsrc/include/vcpkg/base/graphs.h
  toolsrc/include/vcpkg/base/util.h
  toolsrc/src/vcpkg-test/arguments.cpp
  toolsrc/src/vcpkg-test/catch.cpp
  toolsrc/src/vcpkg-test/chrono.cpp
  toolsrc/src/vcpkg-test/dependencies.cpp
  toolsrc/src/vcpkg-test/files.cpp
  toolsrc/src/vcpkg-test/paragraph.cpp
  toolsrc/src/vcpkg-test/plan.cpp
  toolsrc/src/vcpkg-test/specifier.cpp
  toolsrc/src/vcpkg-test/statusparagraphs.cpp
  toolsrc/src/vcpkg-test/strings.cpp
  toolsrc/src/vcpkg-test/supports.cpp
  toolsrc/src/vcpkg-test/update.cpp
  toolsrc/src/vcpkg-test/util.cpp
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/base/hash.cpp
  toolsrc/src/vcpkg/base/system.cpp
  toolsrc/src/vcpkg/base/system.print.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.autocomplete.cpp
  toolsrc/src/vcpkg/commands.dependinfo.cpp
  toolsrc/src/vcpkg/commands.edit.cpp
  toolsrc/src/vcpkg/commands.exportifw.cpp
  toolsrc/src/vcpkg/commands.xvsinstances.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/export.cpp
  toolsrc/src/vcpkg/install.cpp
  toolsrc/src/vcpkg/logicexpression.cpp
  toolsrc/src/vcpkg/metrics.cpp
  toolsrc/src/vcpkg/paragraphs.cpp
  toolsrc/src/vcpkg/postbuildlint.cpp
  toolsrc/src/vcpkg/statusparagraphs.cpp
  toolsrc/src/vcpkg/tools.cpp
  toolsrc/src/vcpkg/vcpkgpaths.cpp
  toolsrc/src/vcpkg/versiont.cpp
Labels: internal

#7374 [jsonnet]Upgrade version to 0.13.0
  ports/jsonnet/001-enable-msvc.patch
  ports/jsonnet/CONTROL
  ports/jsonnet/portfile.cmake
Labels: internal

#7754 [vcpkg] allow multiple spaces in a comma list
  toolsrc/src/vcpkg/parse.cpp
Labels: internal

#7434 [gdal]Fix dependent ports in static builds.
  ports/gdal/CONTROL
  ports/gdal/portfile.cmake
Labels: internal

#7687 [vcpkg]Port toolchains
  scripts/get_triplet_environment.cmake
  scripts/ports.cmake
  toolsrc/VERSION.txt
  toolsrc/include/vcpkg/base/util.h
  toolsrc/include/vcpkg/build.h
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/dependencies.cpp
Labels: internal, vcpkg feature

#7568 [tensorflow] add new port for linux
  ports/tensorflow-cc/CONTROL
  ports/tensorflow-cc/TensorflowCCConfig.cmake
  ports/tensorflow-cc/file-exists.patch
  ports/tensorflow-cc/portfile.cmake
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: internal, wip

#7769 [paho-mqttpp3] Fix missing reference to C library headers
  ports/paho-mqttpp3/CONTROL
  ports/paho-mqttpp3/fix-include-path.patch
  ports/paho-mqttpp3/portfile.cmake
Labels: internal

#7768 [fribidi]Fix static library suffix in windows-static
  ports/fribidi/CONTROL
  ports/fribidi/fix-win-static-suffix.patch
  ports/fribidi/portfile.cmake
Labels: internal

#7764 [luajit]Separate debug/release build path and fix generate pdbs.
  ports/luajit/002-fix-build-path.patch
  ports/luajit/CONTROL
  ports/luajit/portfile.cmake
Labels: internal

#7767 [embree3] Fix install path
  ports/embree3/CONTROL
  ports/embree3/fix-InstallPath.patch
  ports/embree3/portfile.cmake
Labels: internal

#7747 [openimageio]Fix find correct debug/release openexr libraries.
  ports/openimageio/CONTROL
  ports/openimageio/fix_find_openexr.patch
  ports/openimageio/portfile.cmake
Labels: internal

#7712 [leptonica]Add dependency port libwebp and fix find libwebp in debug/release
  ports/leptonica/CONTROL
  ports/leptonica/find-dependency.patch
  ports/leptonica/fix-find-libwebp.patch
  ports/leptonica/portfile.cmake
Labels: internal

#7816 [vcpkg] Fix gcc-9 warning
  toolsrc/src/vcpkg/export.cpp
Labels: internal

#7316 [gtest]Re-fix port_main/port_maind libraries path and add gmock cmake files.
  ports/gtest/CONTROL
  ports/gtest/fix-gmock-cmake.patch
  ports/gtest/fix-main-lib-path.patch
  ports/gtest/portfile.cmake
  ports/gtest/usage
Labels: internal

#7864 [vcpkg] Move do_build_package_and_clean_buildtrees() above generating vcpkg_abi_info.txt so it will be included in the package.
  toolsrc/src/vcpkg/build.cpp
Labels: internal

#7885 [glfw3]Add more information about installing dependencies.
  ports/glfw3/CONTROL
  ports/glfw3/portfile.cmake
Labels: internal

#7564 [clue] Add new port
  ports/clue/CMakeLists.txt
  ports/clue/CONTROL
  ports/clue/portfile.cmake
Labels: internal

#7563 [status-value-lite, type-lite, value-ptr-lite] Add new ports
  ports/status-value-lite/CONTROL
  ports/status-value-lite/portfile.cmake
  ports/type-lite/CONTROL
  ports/type-lite/portfile.cmake
  ports/value-ptr-lite/CONTROL
  ports/value-ptr-lite/portfile.cmake
Labels: internal

#7562 [kvasir-mpl] Add new port
  ports/kvasir-mpl/CONTROL
  ports/kvasir-mpl/portfile.cmake
Labels: internal

#7977 [libp7client] Rename port folder to lowercase
  ports/libp7client/CONTROL
  ports/libp7client/fix-runtime-library.patch
  ports/libp7client/portfile.cmake
Labels: internal

#7972 [libpng] Fix find_package() in CONFIG mode (#7968)
  ports/libpng/CONTROL
  ports/libpng/libpngConfig.cmake
  ports/libpng/portfile.cmake
Labels: internal

#7888 [openblas]Enable x86 build and fix usage errors.
  ports/openblas/CONTROL
  ports/openblas/fix-redefinition-function.patch
  ports/openblas/openblas_common.h
  ports/openblas/portfile.cmake
Labels: internal

#7963 [glib] Fix install config.h
  ports/glib/CMakeLists.txt
  ports/glib/CONTROL
  ports/glib/portfile.cmake
Labels: internal
