Repository microsoft/vcpkg, pull requests merged in 2019-04, with the labels that each got.

#5734 Update CGAL to version 4.14
  ports/cgal/CONTROL
  ports/cgal/portfile.cmake
Labels: wip

#5878 [vcpkg-fetch] Set git subpath to mingw32\bin\git.exe to fix execution in containers
  scripts/vcpkgTools.xml
Labels: internal

#5919 [live555] Update the download path
  ports/live555/CONTROL
  ports/live555/portfile.cmake
Labels: internal

#5923 [openmesh]Update version to 8.0
  ports/openmesh/CONTROL
  ports/openmesh/portfile.cmake
Labels: internal

#5924 [Thrift] Updates 2019.03.29
  ports/thrift/CONTROL
  ports/thrift/portfile.cmake
  scripts/toolchains/windows.cmake
Labels: internal

#5930 [milerius-sfml-imgui] Fix find_package issue
  ports/milerius-sfml-imgui/CONTROL
  ports/milerius-sfml-imgui/FixFindPackageIssue.patch
  ports/milerius-sfml-imgui/portfile.cmake
Labels: internal

#5933 [RocksDB] Updates 2019.03.29
  ports/rocksdb/0004-use-find-package.patch
  ports/rocksdb/CONTROL
  ports/rocksdb/portfile.cmake
Labels: internal

#5932 [date] Fix failures in UWP with latest commit
  ports/date/CONTROL
  ports/date/fix-date.patch
  ports/date/portfile.cmake
Labels: internal

#5954 [qca] don't use port dir for temp
  ports/qca/CONTROL
  ports/qca/portfile.cmake
Labels: internal

#5940 [gdal] Apply conditional patching
  ports/gdal/CONTROL
  ports/gdal/portfile.cmake
Labels: internal

#5969 [freeimage] fixup dependencies
  ports/freeimage/CONTROL
Labels: internal

#5702 Update to cmake 3.14 (allow compilation with VS2019RC v142)
  bootstrap-vcpkg.sh
  ports/darknet/portfile.cmake
  ports/folly/portfile.cmake
  ports/libmodbus/CONTROL
  ports/libmodbus/portfile.cmake
  ports/libodb-sqlite/CMakeLists.txt
  ports/libodb-sqlite/CONTROL
  ports/openssl-windows/CONTROL
  ports/openssl-windows/portfile.cmake
  ports/sqlitecpp/0001-Find-external-sqlite3.patch
  ports/sqlitecpp/CONTROL
  ports/sqlitecpp/portfile.cmake
  ports/tbb/portfile.cmake
  scripts/bootstrap.sh
  scripts/cmake/vcpkg_configure_cmake.cmake
  scripts/vcpkgTools.xml
Labels: wip

#5928 [Tbb] Updates 2019.03.29
  ports/tbb/CONTROL
  ports/tbb/portfile.cmake
Labels: internal

#5925 [g2o] Fix g2o:x64-windows failed with POST_BUILD_CHECKS_FAILED.#4098
  ports/g2o/CONTROL
  ports/g2o/portfile.cmake
Labels: internal

#5922 [angle] Fix regressions introduced in #4862:
  ports/angle/CMakeLists.txt
  ports/angle/CONTROL
  ports/angle/portfile.cmake
Labels: internal

#6028 [openvdb] Fix openvdb[tools] build failures
  ports/openvdb/0001-fix-cmake-modules.patch
  ports/openvdb/0003-build-only-necessary-targets.patch
  ports/openvdb/0004-add-necessary-head.patch
  ports/openvdb/CONTROL
  ports/openvdb/portfile.cmake
Labels: internal

#6046 [devil/libcopp/spaceland] stable cmake config
  ports/devil/CONTROL
  ports/devil/portfile.cmake
  ports/libcopp/CONTROL
  ports/libcopp/portfile.cmake
  ports/spaceland/CONTROL
  ports/spaceland/portfile.cmake
Labels: internal

#6037 Print what port installed confliciting files
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/src/vcpkg/install.cpp
Labels: internal

#6064 [libpqxx]Update to version 6.4.3
  ports/libpqxx/CMakeLists.txt
  ports/libpqxx/CONTROL
  ports/libpqxx/fix-deprecated-bug.patch
  ports/libpqxx/portfile.cmake
Labels: internal

#6065 [Glog]Upgrades 2019.03.29
  ports/glog/CONTROL
  ports/glog/glog_disable_debug_postfix.patch
  ports/glog/portfile.cmake
Labels: internal

#6096 [embree3] Disable parallel configure due to writes to source directory
  ports/embree3/CONTROL
  ports/embree3/portfile.cmake
Labels: internal

#6100 [tbb] Fix config path
  ports/tbb/CONTROL
  ports/tbb/portfile.cmake
Labels: internal, wip

#5844 [libuuid]Add warning to non-unix platform when building.
  ports/azure-storage-cpp/CONTROL
  ports/azure-storage-cpp/builtin-uuid-osx.patch
  ports/azure-storage-cpp/portfile.cmake
  ports/azure-storage-cpp/pplx-do-while.patch
  ports/libuuid/CONTROL
  ports/libuuid/portfile.cmake
Labels: internal

#6102 [tinyutf8] update to v2.2
  ports/tinyutf8/CONTROL
  ports/tinyutf8/portfile.cmake
Labels: internal

#6041 upgrade to windows MinGit 2.21.0
  ports/fdlibm/CONTROL
  ports/fdlibm/portfile.cmake
  scripts/vcpkgTools.xml
Labels: internal

#5698 [many ports] Updates 2019.03.29
  ports/abseil/CONTROL
  ports/abseil/portfile.cmake
  ports/args/CONTROL
  ports/args/portfile.cmake
  ports/asmjit/CONTROL
  ports/asmjit/portfile.cmake
  ports/aws-sdk-cpp/CONTROL
  ports/aws-sdk-cpp/portfile.cmake
  ports/brynet/CONTROL
  ports/brynet/portfile.cmake
  ports/catch2/CONTROL
  ports/catch2/portfile.cmake
  ports/chakracore/CONTROL
  ports/chakracore/portfile.cmake
  ports/cimg/CONTROL
  ports/cimg/portfile.cmake
  ports/clara/CONTROL
  ports/clara/portfile.cmake
  ports/directxmesh/CONTROL
  ports/directxmesh/portfile.cmake
  ports/directxtex/CONTROL
  ports/directxtex/portfile.cmake
  ports/directxtk/CONTROL
  ports/directxtk/portfile.cmake
  ports/eastl/CONTROL
  ports/eastl/portfile.cmake
  ports/exprtk/CONTROL
  ports/exprtk/portfile.cmake
  ports/freetype-gl/CONTROL
  ports/freetype-gl/portfile.cmake
  ports/gdcm2/CONTROL
  ports/gdcm2/portfile.cmake
  ports/glm/CONTROL
  ports/glm/portfile.cmake
  ports/imgui/CONTROL
  ports/imgui/portfile.cmake
  ports/liblinear/CONTROL
  ports/liblinear/portfile.cmake
  ports/luasocket/CONTROL
  ports/luasocket/portfile.cmake
  ports/matio/CONTROL
  ports/matio/portfile.cmake
  ports/nuklear/CONTROL
  ports/nuklear/portfile.cmake
  ports/parson/CONTROL
  ports/parson/portfile.cmake
  ports/re2/CONTROL
  ports/re2/portfile.cmake
  ports/rs-core-lib/CONTROL
  ports/rs-core-lib/portfile.cmake
  ports/unicorn-lib/CONTROL
  ports/unicorn-lib/portfile.cmake
  ports/unicorn/CONTROL
  ports/unicorn/portfile.cmake
  ports/yoga/CONTROL
  ports/yoga/portfile.cmake
Labels: internal

#6136 [eigen3] Fix long path issue in UWP
  ports/eigen3/CONTROL
  ports/eigen3/portfile.cmake
Labels: internal

#6135 [check]Fix always built as debug library.
  ports/check/CONTROL
  ports/check/fix-build-debug-mode.patch
  ports/check/portfile.cmake
Labels: internal

#6130 [armadillo] Use new GitLab repository and enable Linux
  ports/armadillo/ArmadilloConfig.cmake
  ports/armadillo/CONTROL
  ports/armadillo/disable-wrapper.patch
  ports/armadillo/portfile.cmake
  ports/armadillo/usage
Labels: internal

#6176 [live555] update download URL
  ports/live555/portfile.cmake
Labels: internal

#6175 Add exit code
  toolsrc/src/vcpkg.cpp
Labels: internal

#6173 [gdal/pmdk]Update to new version
  ports/gdal/CONTROL
  ports/gdal/portfile.cmake
  ports/pmdk/CONTROL
  ports/pmdk/portfile.cmake
Labels: internal

#6181 [openblas]Disable cross-compiling to fix uwp build.
  ports/openblas/CONTROL
  ports/openblas/portfile.cmake
  ports/openblas/uwp.patch
Labels: internal

#6172 [embree2] Disable parallel configure
  ports/embree2/CONTROL
  ports/embree2/portfile.cmake
Labels: internal

#6186 [rocksdb]Update rocksdb to v6.0.1 and fix patching failure.
  ports/rocksdb/0002-only-build-one-flavor.patch
  ports/rocksdb/0003-zlib-findpackage.patch
  ports/rocksdb/CONTROL
  ports/rocksdb/portfile.cmake
Labels: internal

#6195 [Alembic]Fix error C1803 when using headers from OpenEXR
  ports/alembic/CONTROL
  ports/alembic/fix-C1083.patch
  ports/alembic/portfile.cmake
Labels: internal

#6129 [ade] Add port (taken from PR 5169 by @cenit)
  ports/ade/CONTROL
  ports/ade/portfile.cmake
Labels: internal

#6210 [Jom] Upgrade Jom
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: internal

#6185 [cctz]Update cctz to v2.3 and add dependence benchmark.
  ports/cctz/CMakeLists.txt
  ports/cctz/CONTROL
  ports/cctz/portfile.cmake
Labels: internal

#6207 [devicenameresolver] Add missing <string>
  ports/devicenameresolver/CONTROL
  ports/devicenameresolver/add-string-headfile.patch
  ports/devicenameresolver/portfile.cmake
Labels: internal

#6211 [aws-lambda-cpp]Add warning to non-Linux platform when building
  ports/aws-lambda-cpp/CONTROL
  ports/aws-lambda-cpp/portfile.cmake
Labels: internal

#6222 [clblast] Add new port
  ports/clblast/CONTROL
  ports/clblast/portfile.cmake
Labels: internal

#6131 [date] Update the version to the latest commit.
  ports/date/CONTROL
  ports/date/portfile.cmake
Labels: internal

#6155 [many ports] Updates 2019.04.19
  ports/abseil/CONTROL
  ports/abseil/portfile.cmake
  ports/aws-sdk-cpp/CONTROL
  ports/aws-sdk-cpp/portfile.cmake
  ports/catch2/CONTROL
  ports/catch2/portfile.cmake
  ports/cctz/portfile.cmake
  ports/chakracore/CONTROL
  ports/chakracore/portfile.cmake
  ports/cimg/CONTROL
  ports/cimg/portfile.cmake
  ports/forest/CONTROL
  ports/forest/portfile.cmake
  ports/glm/CONTROL
  ports/glm/portfile.cmake
  ports/libpng/CONTROL
  ports/libpng/portfile.cmake
  ports/libuv/CONTROL
  ports/libuv/portfile.cmake
  ports/lz4/CONTROL
  ports/lz4/portfile.cmake
  ports/ms-gsl/CONTROL
  ports/ms-gsl/portfile.cmake
  ports/parson/CONTROL
  ports/parson/portfile.cmake
  ports/rs-core-lib/CONTROL
  ports/rs-core-lib/portfile.cmake
  ports/stb/CONTROL
  ports/stb/portfile.cmake
  ports/thrift/CONTROL
  ports/thrift/portfile.cmake
  ports/torch-th/CONTROL
  ports/torch-th/portfile.cmake
  ports/trompeloeil/CONTROL
  ports/trompeloeil/portfile.cmake
  ports/unicorn-lib/CONTROL
  ports/unicorn-lib/portfile.cmake
  ports/unicorn/CONTROL
  ports/unicorn/portfile.cmake
  ports/yoga/CONTROL
  ports/yoga/portfile.cmake
  ports/zeromq/CONTROL
  ports/zeromq/portfile.cmake
Labels: internal

#6269 [fmi4cpp] Update to 0.7.0
  ports/fmi4cpp/CONTROL
  ports/fmi4cpp/portfile.cmake
Labels: internal

#6188 [ceres,jxrlib,zziplib] Fixes for non-windows
  ports/ceres/0001_add_missing_include_path.patch
  ports/ceres/0002_cmakelists_fixes.patch
  ports/ceres/0003_remove_unnecessary_cmake_modules.patch
  ports/ceres/0004_use_glog_target.patch
  ports/ceres/0005_fix_exported_ceres_config.patch
  ports/ceres/CONTROL
  ports/ceres/portfile.cmake
  ports/jxrlib/CMakeLists.txt
  ports/jxrlib/portfile.cmake
  ports/zziplib/CMakeLists.txt
  ports/zziplib/CONTROL
  ports/zziplib/portfile.cmake
Labels: internal
