Repository microsoft/vcpkg, pull requests merged in 2019-06, with the labels that each got.

#6699 [nrf-ble-driver] Update to 4.1.1; Fix system dependencies message
  ports/nrf-ble-driver/CONTROL
  ports/nrf-ble-driver/portfile.cmake
Labels: internal

#6704 [DOXYGEN]Upgrade doxygen to 1.8.15.
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: internal

#6593 [assimp]Fix lrrXML library dependencies.
  ports/assimp/CONTROL
  ports/assimp/portfile.cmake
  ports/assimp/remove-useless-path.patch
Labels: internal

#6748 [libopusenc]Upgrade version to 0.2.1
  ports/libopusenc/CMakeLists.txt
  ports/libopusenc/CONTROL
  ports/libopusenc/portfile.cmake
Labels: internal

#6736 [entityx][entt] Disable parallel configure
  ports/entityx/CONTROL
  ports/entityx/fix-cmake.patch
  ports/entityx/portfile.cmake
  ports/entt/CONTROL
  ports/entt/portfile.cmake
Labels: internal

#6735 [lz4]Fix conflict file xxhash.h
  ports/lz4/CMakeLists.txt
  ports/lz4/CONTROL
Labels: internal

#6750 [xxhash]Upgrade version to 0.7.0 and fix arm/uwp build errors.
  ports/xxhash/CONTROL
  ports/xxhash/fix-arm-uwp.patch
  ports/xxhash/portfile.cmake
Labels: internal

#6763 [arb]Upgrade version to 2.16.0 and fix build error.
  ports/arb/CONTROL
  ports/arb/fix-build-error.patch
  ports/arb/portfile.cmake
Labels: internal

#6761 [harfbuzz]Upgrade version to 2.5.1 and fix patches.
  ports/harfbuzz/0001-fix-cmake-export.patch
  ports/harfbuzz/0003-remove-broken-test.patch
  ports/harfbuzz/CONTROL
  ports/harfbuzz/find-package-freetype-2.patch
  ports/harfbuzz/portfile.cmake
Labels: internal

#6672 [itpp] Add new port
  ports/itpp/CONTROL
  ports/itpp/fix-linux.patch
  ports/itpp/fix-uwp.patch
  ports/itpp/msvc2013.patch
  ports/itpp/portfile.cmake
Labels: internal

#6773 [zstr] Add new port
  ports/zstr/CONTROL
  ports/zstr/portfile.cmake
Labels: internal

#6793 [vlpp] Upgrade to 0.10.0.0
  ports/vlpp/CMakeLists.txt
  ports/vlpp/CONTROL
  ports/vlpp/portfile.cmake
Labels: internal

#6796 [draco, flatbuffers, forge] Upgrade to new version
  ports/draco/CONTROL
  ports/draco/fix-compile-error-uwp.patch
  ports/draco/fix-uwperror.patch
  ports/draco/portfile.cmake
  ports/flatbuffers/CONTROL
  ports/flatbuffers/fix-uwp-build.patch
  ports/flatbuffers/ignore_use_of_cmake_toolchain_file.patch
  ports/flatbuffers/no-werror.patch
  ports/flatbuffers/portfile.cmake
  ports/forge/CONTROL
  ports/forge/fix-static_build.patch
  ports/forge/forge_targets_fix.patch
  ports/forge/portfile.cmake
  ports/forge/static_build.patch
Labels: internal

#6482 [libjpeg-turbo] Upgrades 2019.05.08
  ports/libjpeg-turbo/CONTROL
  ports/libjpeg-turbo/add-options-for-exes-docs-headers.patch
  ports/libjpeg-turbo/portfile.cmake
Labels: internal

#6826 [vcpkg] Apply clang format
  toolsrc/include/vcpkg/base/chrono.h
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/src/tests.arguments.cpp
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/archives.cpp
  toolsrc/src/vcpkg/base/chrono.cpp
  toolsrc/src/vcpkg/base/downloads.cpp
  toolsrc/src/vcpkg/base/files.cpp
  toolsrc/src/vcpkg/base/system.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.ci.cpp
  toolsrc/src/vcpkg/commands.create.cpp
  toolsrc/src/vcpkg/commands.dependinfo.cpp
  toolsrc/src/vcpkg/commands.edit.cpp
  toolsrc/src/vcpkg/commands.import.cpp
  toolsrc/src/vcpkg/commands.integrate.cpp
  toolsrc/src/vcpkg/export.cpp
  toolsrc/src/vcpkg/install.cpp
  toolsrc/src/vcpkg/packagespecparseresult.cpp
  toolsrc/src/vcpkg/paragraphs.cpp
  toolsrc/src/vcpkg/tools.cpp
  toolsrc/src/vcpkg/userconfig.cpp
Labels: internal

#6762 [paho-mqtt] Upgrade to 1.3.0
  ports/paho-mqtt/CONTROL
  ports/paho-mqtt/fix-install-path.patch
  ports/paho-mqtt/fix-unresolvedsymbol-arm.patch
  ports/paho-mqtt/portfile.cmake
Labels: internal

#6840 [boost-thread] Fix old patches
  ports/boost-thread/CONTROL
  ports/boost-thread/avoid-winapi.patch
Labels: internal

#6839 [qca]Upgrade version to 2.2.1 and fix build error.
  ports/qca/0002-fix-build-error.patch
  ports/qca/CONTROL
  ports/qca/portfile.cmake
Labels: internal

#6836 [lcm]Upgrade version to 1.4.0 and fix build error.
  ports/lcm/CONTROL
  ports/lcm/fix-build-error.patch
  ports/lcm/portfile.cmake
Labels: internal

#6844 [vcpkg] Add optional 'Homepage' field to CONTROL
  docs/maintainers/control-files.md
  ports/alembic/CONTROL
  ports/anax/CONTROL
  ports/autobahn/CONTROL
  ports/azure-storage-cpp/CONTROL
  ports/bond/CONTROL
  ports/box2d/CONTROL
  ports/capnproto/CONTROL
  ports/catch2/CONTROL
  ports/cli11/CONTROL
  ports/corrade/CONTROL
  ports/entityx/CONTROL
  ports/entt/CONTROL
  ports/exiv2/CONTROL
  ports/flatbuffers/CONTROL
  ports/fmilib/CONTROL
  ports/g2o/CONTROL
  ports/getopt-win32/CONTROL
  ports/gli/CONTROL
  ports/glibmm/CONTROL
  ports/glm/CONTROL
  ports/globjects/CONTROL
  ports/kd-soap/CONTROL
  ports/magnum-extras/CONTROL
  ports/magnum-integration/CONTROL
  ports/magnum-plugins/CONTROL
  ports/magnum/CONTROL
  ports/mdnsresponder/CONTROL
  ports/minisat-master-keying/CONTROL
  ports/moos-core/CONTROL
  ports/moos-essential/CONTROL
  ports/moos-ui/CONTROL
  ports/mosquitto/CONTROL
  ports/opentracing/CONTROL
  ports/poco/CONTROL
  ports/qca/CONTROL
  ports/rapidjson/CONTROL
  ports/readline-win32/CONTROL
  ports/rxqt/CONTROL
  ports/sdl2pp/CONTROL
  ports/spectra/CONTROL
  ports/think-cell-range/CONTROL
  ports/treehopper/CONTROL
  ports/trompeloeil/CONTROL
  ports/uvw/CONTROL
  ports/zstd/CONTROL
  toolsrc/include/vcpkg/sourceparagraph.h
  toolsrc/src/vcpkg/sourceparagraph.cpp
Labels: internal

#6747 [aws-c-common]Upgrade version to 0.3.11
  ports/aws-c-common/CONTROL
  ports/aws-c-common/disable-internal-crt-option.patch
  ports/aws-c-common/fix-dependencey-build-error.patch
  ports/aws-c-common/portfile.cmake
Labels: internal

#6442 [libmysql]Fix build error in linux.
  ports/libmysql/CONTROL
  ports/libmysql/linux_libmysql.patch
  ports/libmysql/portfile.cmake
Labels: internal

#6695 [icu] Enable parallel builds
  ports/icu/fix_parallel_build_on_windows.patch
  ports/icu/portfile.cmake
  scripts/cmake/vcpkg_build_cmake.cmake
  scripts/cmake/vcpkg_common_functions.cmake
  scripts/cmake/vcpkg_execute_build_process.cmake
  toolsrc/include/vcpkg/base/system.h
  toolsrc/src/vcpkg/base/system.cpp
  toolsrc/src/vcpkg/build.cpp
Labels: internal

#6853 [glew] Disable the link option /nodefaultlib and /noentry
  ports/glew/CONTROL
  ports/glew/fix-LNK2019.patch
  ports/glew/portfile.cmake
Labels: internal

#6865 [netcdf-c]Fix build error on linux.
  ports/netcdf-c/CONTROL
  ports/netcdf-c/fix-build-error-on-linux.patch
  ports/netcdf-c/portfile.cmake
Labels: internal

#6876 [glbinding] remove conflict with other opengl ports
  ports/glbinding/CONTROL
  ports/glbinding/portfile.cmake
Labels: internal

#6875 [libsodium/darts-clone] remove conflicting makefile
  ports/darts-clone/CONTROL
  ports/darts-clone/portfile.cmake
  ports/libsodium/CONTROL
  ports/libsodium/portfile.cmake
Labels: internal

#6862 [libbson mongo-c-driver mongo-cxx-driver] upgrades to new revision
  ports/libbson/CONTROL
  ports/libbson/portfile.cmake
  ports/mongo-c-driver/CONTROL
  ports/mongo-c-driver/portfile.cmake
  ports/mongo-cxx-driver/CONTROL
  ports/mongo-cxx-driver/disable_test_and_example.patch
  ports/mongo-cxx-driver/portfile.cmake
Labels: internal

#6861 [zydis] Add new port
  ports/zydis/CONTROL
  ports/zydis/portfile.cmake
Labels: internal

#6879 [harfbuzz] Propagate dependency on glib downstream
  ports/harfbuzz/CONTROL
  ports/harfbuzz/portfile.cmake
Labels: internal

#6851 [taglib]Upgrade version to 1.11.1-20190531.
  ports/taglib/CONTROL
  ports/taglib/portfile.cmake
Labels: internal

#6880 retry on flaky linker
  scripts/cmake/vcpkg_execute_build_process.cmake
Labels: internal

#6896 [sndfile/libsndfile] remove duplicate port, forward to libsndfile
  ports/libsndfile/CONTROL
  ports/sndfile/CONTROL
  ports/sndfile/portfile.cmake
  ports/sndfile/uwp-createfile-getfilesize-addendum.patch
  ports/sndfile/uwp-createfile-getfilesize.patch
Labels: internal

#6894 [sqlite-orm] fix tag, update hash
  ports/sqlite-orm/CONTROL
  ports/sqlite-orm/portfile.cmake
Labels: internal

#6767 [itk] Upgrade to 5.0.0
  ports/itk/CONTROL
  ports/itk/fix_conflict_with_openjp2_pc.patch
  ports/itk/portfile.cmake
Labels: internal

#6769 [OpenIGTLInk] Add new port
  ports/openigtlink/CONTROL
  ports/openigtlink/portfile.cmake
Labels: internal

#6893 [libsquish] fix flaky build
  ports/libsquish/CONTROL
  ports/libsquish/portfile.cmake
Labels: internal

#6932 [aws-sdk-cpp]Upgrade to 1.7.116
  ports/aws-sdk-cpp/CONTROL
  ports/aws-sdk-cpp/portfile.cmake
Labels: internal

#6938 [forest] move to 12.0.0
  ports/forest/CONTROL
  ports/forest/portfile.cmake
Labels: internal

#6901 [opencv]Fix build error with feature gdcm: cannot find openjp2.
  ports/opencv/0006-fix-missing-openjp2.patch
  ports/opencv/CONTROL
  ports/opencv/portfile.cmake
Labels: internal

#6900 [leveldb] Port update
  ports/leveldb/CMakeLists.txt
  ports/leveldb/CONTROL
  ports/leveldb/fix-install_path.patch
  ports/leveldb/msvc_code_fix.diff
  ports/leveldb/portfile.cmake
Labels: internal

#6928 [blosc] Fix the bug when building release-only.
  ports/blosc/CONTROL
  ports/blosc/portfile.cmake
Labels: internal

#6855 [libwebsockets] Fix build error on Linux
  ports/libwebsockets/0001-Fix-UWP.patch
  ports/libwebsockets/CONTROL
  ports/libwebsockets/portfile.cmake
Labels: internal

#5777 [realsense2] Update to v2.19.0
  ports/realsense2/CONTROL
  ports/realsense2/portfile.cmake
Labels: wip

#5275 [realsense2] Enable OpenNI2 driver option
  ports/realsense2/CONTROL
  ports/realsense2/fix_openni2.patch
  ports/realsense2/portfile.cmake
Labels: help wanted, wip

#6765 [nvtt]Upgrade version to 2.1.1 and fix build error on windows.
  ports/nvtt/001-define-value-for-HAVE_UNISTD_H-in-mac-os.patch
  ports/nvtt/CONTROL
  ports/nvtt/fix-build-error.patch
  ports/nvtt/portfile.cmake
Labels: internal

#6930 [log4cplus]Fix lnk2019 errors when using log4cplus.
  ports/log4cplus/CONTROL
  ports/log4cplus/fix-usage-error.patch
  ports/log4cplus/portfile.cmake
Labels: internal

#6929 [sdl2-mixer]Fix build error with feature opusfile.
  ports/sdl2-mixer/CMakeLists.txt
  ports/sdl2-mixer/CONTROL
Labels: internal

#6927 [qt5-declarative]Fix error when building release-only.
  ports/qt5-declarative/CONTROL
  ports/qt5-declarative/portfile.cmake
Labels: internal

#6943 address qhull flaky build with msvc linker
  scripts/cmake/vcpkg_execute_build_process.cmake
Labels: internal

#6924 [spdlog]Add feature[benchmark] and fix pkgconfig path.
  ports/spdlog/CONTROL
  ports/spdlog/fix-feature-export.patch
  ports/spdlog/portfile.cmake
Labels: internal

#6383 [vcpkg] update python3 to 3.7.3 on windows
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: internal

#6919 [vcpkg] Improve vcpkg::Files::Filesystem error handling
  .gitignore
  toolsrc/CMakeLists.txt
  toolsrc/include/tests.utils.h
  toolsrc/include/vcpkg/base/files.h
  toolsrc/include/vcpkg/base/graphs.h
  toolsrc/include/vcpkg/base/optional.h
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/src/vcpkg/base/downloads.cpp
  toolsrc/src/vcpkg/base/files.cpp
  toolsrc/src/vcpkg/base/strings.cpp
  toolsrc/src/vcpkg/base/system.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.ci.cpp
  toolsrc/src/vcpkg/commands.exportifw.cpp
  toolsrc/src/vcpkg/commands.import.cpp
  toolsrc/src/vcpkg/commands.integrate.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/export.cpp
  toolsrc/src/vcpkg/help.cpp
  toolsrc/src/vcpkg/install.cpp
  toolsrc/src/vcpkg/remove.cpp
  toolsrc/src/vcpkg/tools.cpp
  toolsrc/src/vcpkg/update.cpp
  toolsrc/src/vcpkg/vcpkglib.cpp
Labels: internal

#6945 [msmpi] Fix /MD for static libs.
  ports/msmpi/CONTROL
  ports/msmpi/portfile.cmake
Labels: internal

#6974 [Folly] Disable non-underscore posix names on windows
  ports/folly/CONTROL
  ports/folly/disable-non-underscore-posix-names.patch
  ports/folly/portfile.cmake
Labels: internal

#6970 [xerces-c]Replace the macro DLL_EXPORT with the macro XERCES_DLL_EXPORT
  ports/xerces-c/CONTROL
  ports/xerces-c/portfile.cmake
  ports/xerces-c/remove-dll-export-macro.patch
Labels: internal

#6954 [bond]Upgrade version to 8.1.0 and add Linux support.
  ports/bond/0002_omit_rapidjson.patch
  ports/bond/CONTROL
  ports/bond/fix-install-path.patch
  ports/bond/portfile.cmake
Labels: internal

#6953 [thor] Fix error on Linux.
  ports/thor/CONTROL
  ports/thor/portfile.cmake
Labels: internal

#6971 [netcdf-c] Fix link error.
  ports/netcdf-c/CONTROL
  ports/netcdf-c/hdf5_3.patch
  ports/netcdf-c/portfile.cmake
Labels: internal

#6871 [docs] Add maintainer guidelines
  docs/index.md
  docs/maintainers/control-files.md
  docs/maintainers/maintainer-guide.md
Labels: internal

#6981 Ports Overlay implementation
  docs/specifications/ports-overlay.md
  toolsrc/include/vcpkg/build.h
  toolsrc/include/vcpkg/dependencies.h
  toolsrc/include/vcpkg/postbuildlint.h
  toolsrc/include/vcpkg/sourceparagraph.h
  toolsrc/include/vcpkg/vcpkgcmdarguments.h
  toolsrc/include/vcpkg/vcpkgpaths.h
  toolsrc/src/tests.plan.cpp
  toolsrc/src/tests.update.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.autocomplete.cpp
  toolsrc/src/vcpkg/commands.buildexternal.cpp
  toolsrc/src/vcpkg/commands.ci.cpp
  toolsrc/src/vcpkg/commands.dependinfo.cpp
  toolsrc/src/vcpkg/commands.edit.cpp
  toolsrc/src/vcpkg/commands.search.cpp
  toolsrc/src/vcpkg/commands.upgrade.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/export.cpp
  toolsrc/src/vcpkg/help.cpp
  toolsrc/src/vcpkg/install.cpp
  toolsrc/src/vcpkg/postbuildlint.cpp
  toolsrc/src/vcpkg/remove.cpp
  toolsrc/src/vcpkg/update.cpp
  toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
  toolsrc/src/vcpkg/vcpkgpaths.cpp
  toolsrc/vcpkg/vcpkg.vcxproj
  toolsrc/vcpkglib/vcpkglib.vcxproj
  toolsrc/vcpkgmetricsuploader/vcpkgmetricsuploader.vcxproj
  toolsrc/vcpkgtest/vcpkgtest.vcxproj
Labels: internal, vcpkg feature, wip

#6967 [ppconsul] remove conflict with json11
  ports/json11/CONTROL
  ports/json11/destination.patch
  ports/json11/json11-config.cmake
  ports/json11/portfile.cmake
  ports/ppconsul/CONTROL
  ports/ppconsul/cmake_build.patch
  ports/ppconsul/portfile.cmake
Labels: internal

#6931 [flann]Upgrade version to 1.9.1 and fix build error.
  ports/flann/CONTROL
  ports/flann/fix-build-error.patch
  ports/flann/portfile.cmake
Labels: internal

#7008 [libtins]Upgrade version to 4.2 and adds dependent ports to new version.
  ports/libtins/CONTROL
  ports/libtins/portfile.cmake
Labels: internal

#7002 [--overlay-ports] Show location of overriden ports during install plan
  toolsrc/include/vcpkg/dependencies.h
  toolsrc/src/vcpkg/commands.ci.cpp
  toolsrc/src/vcpkg/commands.upgrade.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/install.cpp
Labels: internal

#6787 [darknet] update to latest release
  ports/darknet/CONTROL
  ports/darknet/fix_cmakelists.patch
  ports/darknet/portfile.cmake
Labels: wip

#7031 Update cnl
  ports/cnl/CONTROL
  ports/cnl/portfile.cmake
Labels: internal

#7022 [armadillo] Fix build error in Linux
  ports/armadillo/CONTROL
  ports/armadillo/portfile.cmake
Labels: internal

#7021 [nana][fmi4cpp] Fix Visual Studio 2019 deprecates <experimental/filesystem>
  ports/fmi4cpp/CONTROL
  ports/fmi4cpp/fix-build_error.patch
  ports/fmi4cpp/portfile.cmake
  ports/nana/CONTROL
  ports/nana/fix-build-error.patch
  ports/nana/portfile.cmake
Labels: internal

#7020 [libpmemobj-cpp] Add new port
  ports/libpmemobj-cpp/CONTROL
  ports/libpmemobj-cpp/portfile.cmake
Labels: internal

#7019 [qt5-base]Add execute permission when installing executables in Linux.
  ports/qt5-base/CONTROL
  ports/qt5-base/portfile.cmake
Labels: internal

#7035 [libmikmod] patch cmake warning
  ports/libmikmod/CONTROL
  ports/libmikmod/cmake_policy.patch
  ports/libmikmod/portfile.cmake
Labels: internal

#7036 [libfabric] reorder patch
  ports/libfabric/CONTROL
  ports/libfabric/add_additional_includes.patch
Labels: internal

#7039 [docs]Update cmake docs
  docs/maintainers/portfile-functions.md
  docs/maintainers/vcpkg_configure_cmake.md
  docs/maintainers/vcpkg_execute_build_process.md
  docs/maintainers/vcpkg_extract_source_archive_ex.md
  docs/maintainers/vcpkg_find_acquire_program.md
  scripts/cmake/vcpkg_configure_cmake.cmake
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake
Labels: internal

#6969 [libevent] Upgrade to version 2.1.10
  ports/fizz/fix-build_error.patch
  ports/fizz/portfile.cmake
  ports/libevent/CONTROL
  ports/libevent/fix-arm_build.patch
  ports/libevent/fix-file_path.patch
  ports/libevent/fix-target-files.patch
  ports/libevent/portfile.cmake
Labels: internal

#6864 [openvdb]Upgrade version to 6.1.0
  ports/openvdb/0001-fix-cmake-modules.patch
  ports/openvdb/0001-remove-pkgconfig.patch
  ports/openvdb/0002-add-custom-options.patch
  ports/openvdb/0002-fix-cmake-modules.patch
  ports/openvdb/0003-build-only-necessary-targets.patch
  ports/openvdb/0003-fix-cmake.patch
  ports/openvdb/0004-add-necessary-head.patch
  ports/openvdb/CONTROL
  ports/openvdb/blosc.patch
  ports/openvdb/portfile.cmake
Labels: internal

#7047 [Boost-variant] Upgrade to 1.70.0
  ports/boost-variant/CONTROL
  ports/boost-variant/fix-regression-1.70.patch
  ports/boost-variant/portfile.cmake
Labels: internal

#7046 [libmupdf] Update the port to version 1.15.
  ports/libmupdf/CMakeLists.txt
  ports/libmupdf/CONTROL
  ports/libmupdf/portfile.cmake
Labels: internal

#6892 [angle] Update to latest master
  ports/angle/CMakeLists.txt
  ports/angle/CONTROL
  ports/angle/portfile.cmake
Labels: internal

#7052 [libmikmod] resolve ninja error (-w dupbuild=err)
  ports/libmikmod/CONTROL
  ports/libmikmod/cmake_policy.patch
  ports/libmikmod/name_conflict.patch
  ports/libmikmod/portfile.cmake
Labels: internal

#7054 [restclient-cpp] disable tests
  ports/restclient-cpp/CONTROL
  ports/restclient-cpp/portfile.cmake
Labels: internal

#7055 [libftdi] resolve ninja error (-w dupbuild=err)
  ports/libftdi/CONTROL
  ports/libftdi/export-cmake.patch
  ports/libftdi/portfile.cmake
  ports/libftdi/shared-static.patch
Labels: internal

#7058 [libxslt] Update the version to 1.1.33 and change the URL.
  ports/libxslt/CONTROL
  ports/libxslt/portfile.cmake
Labels: internal

#7053 Triplets Overlay Implementation
  scripts/ports.cmake
  toolsrc/include/vcpkg/vcpkgcmdarguments.h
  toolsrc/include/vcpkg/vcpkgpaths.h
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/help.cpp
  toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
  toolsrc/src/vcpkg/vcpkgpaths.cpp
Labels: internal, vcpkg feature

#7073 [flann] fix flaky config
  ports/flann/CONTROL
  ports/flann/portfile.cmake
Labels: internal

#7083 [asio] fix flaky build
  ports/asio/CMakeLists.txt
  ports/asio/CONTROL
  ports/asio/portfile.cmake
Labels: internal

#7090 [zziplib] fix flaky build
  ports/zziplib/CONTROL
  ports/zziplib/portfile.cmake
Labels: internal

#7095 [vcpkg-integrate] Improve spelling, help, and autocomplete.
  toolsrc/src/vcpkg/commands.integrate.cpp
Labels: internal

#7097 [libpmemobj-cpp] fix flaky config
  ports/libpmemobj-cpp/CONTROL
  ports/libpmemobj-cpp/portfile.cmake
Labels: internal

#7086 [vcpkg] fail archived port install when decompression fails
  toolsrc/src/vcpkg/build.cpp
Labels: internal

#7057 [freetype] Upgrade to version 2.10.0
  ports/freetype/0002-Add-CONFIG_INSTALL_PATH-option.patch
  ports/freetype/0003-Fix-UWP.patch
  ports/freetype/0004-Fix-DLL-install.patch
  ports/freetype/CONTROL
  ports/freetype/portfile.cmake
Labels: internal

#7074 [vcpkg_configure_cmake] Add NO_CHARSET_FLAG option
  docs/maintainers/vcpkg_configure_cmake.md
  ports/duilib/CONTROL
  ports/duilib/portfile.cmake
  ports/msix/CONTROL
  ports/msix/portfile.cmake
  ports/thrift/CONTROL
  ports/thrift/portfile.cmake
  ports/tidy-html5/CONTROL
  ports/tidy-html5/portfile.cmake
  scripts/cmake/vcpkg_configure_cmake.cmake
  scripts/toolchains/windows.cmake
  toolsrc/src/vcpkg/build.cpp
Labels: internal
