Repository microsoft/vcpkg, pull requests merged in 2020-05, with the labels that each got.

#11036 [libqcow] Initial port
  ports/libqcow/CMakeLists.txt
  ports/libqcow/CONTROL
  ports/libqcow/Config.cmake.in
  ports/libqcow/macos_fixes.patch
  ports/libqcow/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11039 [abseil] Configure abseil to use std:: types when feature cxx17 is enabled
  ports/abseil/CONTROL
  ports/abseil/fix-use-cxx17-stdlib-types.patch
  ports/abseil/portfile.cmake
Labels: reviewed

#11026 [qt5] fix version in some qt related CONTROL files
  ports/qt5-androidextras/CONTROL
  ports/qt5-canvas3d/CONTROL
  ports/qt5-doc/CONTROL
  ports/qt5-serialbus/CONTROL
  ports/qt5-translations/CONTROL
  ports/qt5-wayland/CONTROL
  ports/qt5-webengine/CONTROL
  ports/qt5-webglplugin/CONTROL
  ports/qt5-x11extras/CONTROL
Labels: reviewed

#11016 [Arrow] Add filesystem feature
  ports/arrow/CONTROL
  ports/arrow/portfile.cmake
Labels: reviewed

#10992 [metrohash] installation fix
  ports/metrohash/CMakeLists.txt
  ports/metrohash/CONTROL
  ports/metrohash/portfile.cmake
Labels: reviewed

#10936 [nana] Revert 1 darkcacok patch nana
  ports/nana/CONTROL
  ports/nana/config.cmake.in
Labels: reviewed

#10912 [alembic] linux fixes
  ports/alembic/CONTROL
  ports/alembic/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11020 [mstch] Add new port
  ports/mstch/CONTROL
  ports/mstch/do-not-force-release.patch
  ports/mstch/portfile.cmake
Labels: reviewed

#10591 [civetweb] Update to version 1.12
  ports/civetweb/CONTROL
  ports/civetweb/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10253 [imgui] Add feature bindings and remove feature example
  ports/azure-kinect-sensor-sdk/CONTROL
  ports/azure-kinect-sensor-sdk/fix-dependency-imgui.patch
  ports/azure-kinect-sensor-sdk/portfile.cmake
  ports/imgui/CMakeLists.txt
  ports/imgui/CONTROL
  ports/imgui/portfile.cmake
  ports/libigl/CONTROL
Labels: internal, reviewed

#10886 [opencv4] Add GTK support for opencv4 portfile
  ports/opencv4/CONTROL
  ports/opencv4/portfile.cmake
Labels: reviewed

#10010 [libbson/mongo-c-driver] Update to 1.16.1
  ports/libbson/CONTROL
  ports/libbson/fix-static-cmake.patch
  ports/libbson/fix-uwp.patch
  ports/libbson/portfile.cmake
  ports/libbson/usage
  ports/mongo-c-driver/CONTROL
  ports/mongo-c-driver/disable-static-when-dynamic-build.patch
  ports/mongo-c-driver/fix-arm-build.patch
  ports/mongo-c-driver/fix-dependency-libbson.patch
  ports/mongo-c-driver/portfile.cmake
  ports/mongo-c-driver/usage
  ports/mongo-cxx-driver/fix-dependency-libbson.patch
  ports/mongo-cxx-driver/fix-dependency-mongocdriver.patch
  ports/mongo-cxx-driver/portfile.cmake
Labels: internal, needs-further-review, reviewed

#11066 [nowide] Add new port
  ports/nowide/CONTROL
  ports/nowide/portfile.cmake
Labels: needs-further-review

#8749 [vcpkg] Add new function vcpkg_copy_tools
  docs/maintainers/maintainer-guide.md
  docs/maintainers/portfile-functions.md
  docs/maintainers/vcpkg_clean_executables_in_bin.md
  docs/maintainers/vcpkg_copy_tools.md
  ports/cpuinfo/CONTROL
  ports/cpuinfo/portfile.cmake
  ports/czmq/CONTROL
  ports/czmq/portfile.cmake
  ports/libsvm/CONTROL
  ports/libsvm/portfile.cmake
  ports/nanomsg/CONTROL
  ports/nanomsg/portfile.cmake
  ports/uriparser/CONTROL
  ports/uriparser/portfile.cmake
  ports/zyre/CONTROL
  ports/zyre/portfile.cmake
  scripts/cmake/vcpkg_clean_executables_in_bin.cmake
  scripts/cmake/vcpkg_common_functions.cmake
  scripts/cmake/vcpkg_copy_tools.cmake
Labels: reviewed

#10295 [llvm] Update to version 10.0.0 and add new features
  ports/halide/CONTROL
  ports/halide/fix-install-path.patch
  ports/halide/portfile.cmake
  ports/llvm/0001-allow-to-use-commas.patch
  ports/llvm/0002-fix-install-paths.patch
  ports/llvm/CONTROL
  ports/llvm/fix-build-error.patch
  ports/llvm/fix-linux-build.patch
  ports/llvm/install-clang-modules-to-share.patch
  ports/llvm/install-llvm-modules-to-share.patch
  ports/llvm/portfile.cmake
  scripts/ci.baseline.txt
Labels: needs-further-review, reviewed

#11166 [vcpkg] Add disk space report on Linux.
  scripts/azure-pipelines/linux/azure-pipelines.yml
  scripts/azure-pipelines/osx/azure-pipelines.yml
Labels: infrastructure, internal

#11111 [qt5] Add -j to make to parallelize on Linux and MacOS
  ports/qt5-base/CONTROL
  ports/qt5-base/cmake/install_qt.cmake
  scripts/cmake/vcpkg_build_qmake.cmake
Labels: internal

#11175 [vcpkg] Point README.md to the correct status badge.
  README.md
Labels: documentation, internal

#11171 [vcpkg] Add telemetry notice to `README.md`.
  README.md
Labels: documentation, internal

#11190 [llvm] Baseline LLVM on Linux to restore the ability to merge PRs.
  scripts/ci.baseline.txt
Labels: internal

#11189 [vcpkg] Add tombstone deletion scripts.
  scripts/azure-pipelines/clean-tombstones.yml
  scripts/azure-pipelines/osx/azure-pipelines.yml
  scripts/azure-pipelines/osx/initialize-environment.sh
  scripts/ci.baseline.txt
Labels: infrastructure, internal

#11022 [libvpx] Added support for build on MacOS and Linux
  ports/libvpx/CONTROL
  ports/libvpx/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10763 [discord-game-sdk] new port
  ports/discord-game-sdk/CMakeLists.txt
  ports/discord-game-sdk/CONTROL
  ports/discord-game-sdk/copyright
  ports/discord-game-sdk/portfile.cmake
  ports/discord-game-sdk/usage
  scripts/ci.baseline.txt
Labels: reviewed

#8579 [apr apr-util] Apr and apr-util for non windows systems
  ports/apr-util/CONTROL
  ports/apr-util/portfile.cmake
  ports/apr-util/use-vcpkg-expat.patch
  ports/apr/CONTROL
  ports/apr/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11105 [vcpkg/scripts] Fix ninja search path on windows and find binaries within vcpkg first
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: needs-further-review

#8871 [libmpeg2] Add new port
  ports/libmpeg2/0001-Add-naive-MSVC-support-to-sources.patch
  ports/libmpeg2/CMakeLists.txt
  ports/libmpeg2/CONTROL
  ports/libmpeg2/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#7849 [OpenCV2] add new "old" port
  ports/darknet/CONTROL
  ports/darknet/portfile.cmake
  ports/opencv2/0002-install-options.patch
  ports/opencv2/0003-force-package-requirements.patch
  ports/opencv2/0004-add-ffmpeg-missing-defines.patch
  ports/opencv2/0005-fix-cuda.patch
  ports/opencv2/CONTROL
  ports/opencv2/portfile.cmake
  ports/opencv3/portfile.cmake
  ports/opencv4/portfile.cmake
  scripts/ci.baseline.txt
Labels: discussion needed

#11202 [vcpkg] always pass VSCMD_SKIP_SENDTELEMETRY=1
  toolsrc/src/vcpkg/base/system.process.cpp
Labels: internal, vcpkg bug

#10901 [rtlsdr] Add new port
  ports/rtlsdr/CONTROL
  ports/rtlsdr/Compile-with-msvc.patch
  ports/rtlsdr/Findlibusb.cmake
  ports/rtlsdr/portfile.cmake
  scripts/ci.baseline.txt
Labels: waiting for response

#10858 [ignition-modular-scripts] Migrate from Bitbucket to GitHub 🤖
  ports/ignition-cmake0/CONTROL
  ports/ignition-cmake0/portfile.cmake
  ports/ignition-cmake2/CONTROL
  ports/ignition-cmake2/portfile.cmake
  ports/ignition-common1/CONTROL
  ports/ignition-common1/portfile.cmake
  ports/ignition-fuel-tools1/CONTROL
  ports/ignition-fuel-tools1/portfile.cmake
  ports/ignition-math4/CONTROL
  ports/ignition-math4/portfile.cmake
  ports/ignition-modularscripts/CONTROL
  ports/ignition-modularscripts/ignition_modular_library.cmake
  ports/ignition-msgs1/CONTROL
  ports/ignition-msgs1/portfile.cmake
  ports/ignition-transport4/CONTROL
  ports/ignition-transport4/portfile.cmake
Labels: needs-further-review, reviewed

#10838 [cuda] Fix find cuda in UNIX
  ports/cuda/CONTROL
  ports/cuda/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal

#8588 [vcpkg] Add x86 support for Linux toolchain
  scripts/toolchains/linux.cmake
Labels: needs-further-review, reviewed

#11213 [vcpkg] Restrict telemetry uploads to TLS 1.2
  scripts/bootstrap.sh
  toolsrc/CMakeLists.txt
  toolsrc/src/vcpkg/metrics.cpp
Labels: internal

#9832 libiconv - Fix ICONV_CONST
  ports/libiconv/CMakeLists.txt
  ports/libiconv/CONTROL
Labels: reviewed

#10856 [glib] Update the usage of string(TOUPPER ...)
  ports/glib/CMakeLists.txt
  ports/glib/CONTROL
  ports/glib/portfile.cmake
Labels: internal, waiting for response

#11051 [freerdp] Update to 2.0.0
  ports/freerdp/CONTROL
  ports/freerdp/fix-libusb.patch
  ports/freerdp/openssl_threads.patch
  ports/freerdp/portfile.cmake
Labels: reviewed

#11178 [wxwidgets] Apply fix to wxWidgets for copy and paste macOS
  ports/wxwidgets/CONTROL
  ports/wxwidgets/fix-macos-clipboard.patch
  ports/wxwidgets/portfile.cmake
Labels: reviewed

#11155 [blend2d] Update to beta_2020-05-04
  ports/blend2d/CONTROL
  ports/blend2d/portfile.cmake
Labels: reviewed

#11124 [libsquish] add missing SQUISH_EXPORT
  ports/libsquish/CONTROL
  ports/libsquish/fix-export-symbols.patch
Labels: reviewed

#11157 [BitSerializer] Update to version 0.9
  ports/bitserializer-cpprestjson/CONTROL
  ports/bitserializer-cpprestjson/portfile.cmake
  ports/bitserializer-rapidjson/CONTROL
  ports/bitserializer-rapidjson/portfile.cmake
  ports/bitserializer/CONTROL
  ports/bitserializer/portfile.cmake
Labels: reviewed

#11048 [gsoap] Add supports for gsoap
  ports/gsoap/CONTROL
  ports/gsoap/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#11153 [skyr-url] Changed skyr-url version number to 1.7.5
  ports/skyr-url/CONTROL
  ports/skyr-url/portfile.cmake
Labels: reviewed

#11163 [lua] Compile as position-independent code
  ports/lua/CMakeLists.txt
  ports/lua/CONTROL
Labels: reviewed

#11195 [dlib] add more granularity in features
  ports/dlib/CONTROL
  ports/dlib/portfile.cmake
Labels: reviewed

#11238 [libqcow] Update baseline
  ports/libqcow/CONTROL
  ports/libqcow/portfile.cmake
Labels: internal, reviewed

#11217 [mongo-c-driver] Fix find_package error
  ports/mongo-c-driver/CONTROL
  ports/mongo-c-driver/usage
Labels: internal, reviewed

#11000 [gainput] imporve cmake search gainput library
  ports/gainput/CONTROL
  ports/gainput/install_as_cmake_package.patch
  ports/gainput/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11234 [vcpkg] Don't build the metrics uploader when metrics are disabled.
  toolsrc/CMakeLists.txt
Labels: reviewed

#9880 [Coin3D] Add new ports for simage, Coin, and SoQt
  ports/coin/CONTROL
  ports/coin/disable-cpackd.patch
  ports/coin/portfile.cmake
  ports/simage/CONTROL
  ports/simage/disable-cpackd.patch
  ports/simage/disable-examples.patch
  ports/simage/disable-tests.patch
  ports/simage/link-flac-library.patch
  ports/simage/link-math-library.patch
  ports/simage/link-ogg-library.patch
  ports/simage/portfile.cmake
  ports/simage/potentially-uninitialized-local-pointer-variable.patch
  ports/soqt/CONTROL
  ports/soqt/disable-cpackd.patch
  ports/soqt/disable-test-code.patch
  ports/soqt/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10567 [opencl] Add build type when installing targets
  ports/opencl/CONTROL
  ports/opencl/portfile.cmake
Labels: internal, reviewed

#11120 [qt5-webengine] Add dep atlmfc to CONTROL. Fix patches for latest. Add some options on linux
  ports/qt5-webengine/CONTROL
  ports/qt5-webengine/common.pri.latest.patch
  ports/qt5-webengine/gl.latest.patch
  ports/qt5-webengine/portfile.cmake
Labels: reviewed

#11233 [vcpkg] Resolve relative overlay ports to the current working directory.
  toolsrc/include/vcpkg/vcpkgpaths.h
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/portfileprovider.cpp
  toolsrc/src/vcpkg/vcpkgpaths.cpp
Labels: internal, reviewed

#10760 [vcpkg] Adding support for finding VS2019 by environment variable
  toolsrc/src/vcpkg/visualstudio.cpp
Labels: needs-feature-review

#11017 [azure-iot-sdk-c] Fixed the CMake config export.
  ports/azure-iot-sdk-c/CONTROL
  ports/azure-iot-sdk-c/fix-cmake.patch
  ports/azure-iot-sdk-c/portfile.cmake
Labels: reviewed

#10613 [gmp,nettle,hogweed] Add new ports
  ports/gmp/CONTROL
  ports/gmp/portfile.cmake
  ports/gmp/prefix.patch
  ports/gmp/runtime.patch
  ports/gmp/vs.build.patch
  ports/nettle/CONTROL
  ports/nettle/gmp.patch
  ports/nettle/name.dir.patch
  ports/nettle/portfile.cmake
  ports/nettle/runtime.hogweed.patch
  ports/nettle/runtime.nettle.patch
  ports/vs-yasm/CONTROL
  ports/vs-yasm/portfile.cmake
  scripts/cmake/vcpkg_install_msbuild.cmake
Labels: needs-feature-review, needs-further-review, reviewed

#11201 [opencv4] Changed dependency on qt5 to qt5-base, closes microsoft/vcpkg#11138
  ports/opencv2/CONTROL
  ports/opencv3/CONTROL
  ports/opencv4/CONTROL
Labels: reviewed

#11246 [sfml] Remove unnecessary patch
  ports/sfml/CONTROL
  ports/sfml/export-win-libs.patch
  ports/sfml/portfile.cmake
Labels: internal, reviewed

#11245 [asmjit] Update to the latest commit
  ports/asmjit/CONTROL
  ports/asmjit/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#11199 [uthenticode] Add new port
  ports/uthenticode/CONTROL
  ports/uthenticode/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11139 [azure-kinect-sensor-sdk] Fix Deploy Azure Kinect Sensor SDK on Windows
  ports/azure-kinect-sensor-sdk/CONTROL
  ports/azure-kinect-sensor-sdk/k4adeploy.ps1
  ports/azure-kinect-sensor-sdk/portfile.cmake
  scripts/buildsystems/msbuild/applocal.ps1
Labels: needs-further-review, reviewed

#11241 [bitserializer-pugixml] Add new port
  ports/bitserializer-pugixml/CONTROL
  ports/bitserializer-pugixml/portfile.cmake
Labels: reviewed

#11232 [ignition-math6] Add new port 🤖
  ports/ignition-cmake2/CONTROL
  ports/ignition-cmake2/portfile.cmake
  ports/ignition-math6/CONTROL
  ports/ignition-math6/portfile.cmake
Labels: reviewed

#11228 [protobuf] Correct protobuf under android (Fix issue #8218)
  ports/protobuf/CONTROL
  ports/protobuf/fix-android-log.patch
  ports/protobuf/portfile.cmake
Labels: reviewed

#11223 [libpq] link libdl on linux
  ports/libpq/CONTROL
  ports/libpq/vcpkg-cmake-wrapper.cmake
Labels: reviewed

#11187 [Allegro] Update to 5.2.6.0
  ports/allegro5/CONTROL
  ports/allegro5/portfile.cmake
Labels: reviewed

#11174 [vcpkg] [llvm] Bump Linux VM memory size and do all operations on the temporary disk.
  ports/llvm/CONTROL
  ports/llvm/portfile.cmake
  scripts/azure-pipelines/azure-pipelines.yml
  scripts/azure-pipelines/clean-tombstones.yml
  scripts/azure-pipelines/linux/azure-pipelines.yml
  scripts/azure-pipelines/linux/create-vmss.ps1
  scripts/azure-pipelines/linux/initialize-environment.sh
  scripts/azure-pipelines/linux/provision-image.sh
  scripts/azure-pipelines/windows/create-vmss.ps1
  scripts/ci.baseline.txt
Labels: infrastructure, internal

#11256 [uthenticode] Update to 1.0.3
  ports/uthenticode/CONTROL
  ports/uthenticode/portfile.cmake
Labels: reviewed

#11148 [VTK/vtk-m] Update VTK to 9.0 and add vtk-m
  ports/lz4/CMakeLists.txt
  ports/lz4/CONTROL
  ports/pcl/CONTROL
  ports/pcl/portfile.cmake
  ports/pegtl-2/CONTROL
  ports/pegtl-2/portfile.cmake
  ports/pegtl/portfile.cmake
  ports/vtk-dicom/CONTROL
  ports/vtk-dicom/portfile.cmake
  ports/vtk-dicom/std.patch
  ports/vtk-m/CONTROL
  ports/vtk-m/portfile.cmake
  ports/vtk/CONTROL
  ports/vtk/FindGDAL.cmake
  ports/vtk/FindHDF5.cmake
  ports/vtk/FindLZ4.patch
  ports/vtk/FindLZMA.patch
  ports/vtk/FindLibHaru.patch
  ports/vtk/FindPostgreSQL.cmake
  ports/vtk/Findproj.patch
  ports/vtk/NoUndefDebug.patch
  ports/vtk/fix-VTKConfig-cmake.patch
  ports/vtk/fix-find-lz4.patch
  ports/vtk/fix-find-lzma.patch
  ports/vtk/fix-proj4.patch
  ports/vtk/fix-pugixml-link.patch
  ports/vtk/fix_ogg_linkage.patch
  ports/vtk/hdf5_static.patch
  ports/vtk/pegtl.patch
  ports/vtk/portfile.cmake
  ports/vtk/pythonwrapper.patch
  ports/vtk/vtkm.patch
Labels: needs-further-review

#11266 [vcpkg][android] Link C++ runtime according to VCPKG_CRT_LINKAGE
  scripts/toolchains/android.cmake
Labels: needs-further-review

#11237 [libzen] Update to 0.4.38
  ports/libzen/CONTROL
  ports/libzen/portfile.cmake
  ports/libzen/vcpkg_support_in_cmakelists.patch
  scripts/ci.baseline.txt
Labels: reviewed

#11218 [speexdsp] Change repo to github
  ports/speexdsp/CONTROL
  ports/speexdsp/portfile.cmake
Labels: internal, reviewed

#9717 [restclient-cpp] Fix portfile and update version.
  ports/restclient-cpp/0001_fix_cmake_linking.patch
  ports/restclient-cpp/CONTROL
  ports/restclient-cpp/portfile.cmake
Labels: waiting for response

#11260 [vcpkg] Update pull request template
  .github/pull_request_template.md
Labels: internal, reviewed

#11302 [vcpkg] Resolve --overlay-ports is only working for relative parths since fix…
  toolsrc/src/vcpkg/portfileprovider.cpp
Labels: reviewed

#10505 [gn, crashpad] Add GN build support and crashpad port
  docs/maintainers/portfile-functions.md
  docs/maintainers/vcpkg_build_gn.md
  docs/maintainers/vcpkg_build_ninja.md
  docs/maintainers/vcpkg_configure_gn.md
  docs/maintainers/vcpkg_find_acquire_program.md
  docs/maintainers/vcpkg_install_gn.md
  ports/crashpad/CONTROL
  ports/crashpad/crashpadConfig.cmake.in
  ports/crashpad/portfile.cmake
  ports/crashpad/zlib.gn
  scripts/ci.baseline.txt
  scripts/cmake/vcpkg_build_gn.cmake
  scripts/cmake/vcpkg_build_ninja.cmake
  scripts/cmake/vcpkg_common_functions.cmake
  scripts/cmake/vcpkg_configure_gn.cmake
  scripts/cmake/vcpkg_find_acquire_program.cmake
  scripts/cmake/vcpkg_install_gn.cmake
Labels: needs-feature-review, reviewed

#11162 [libpng] Fix missing symbols when compiling for ARM
  ports/libpng/CONTROL
  ports/libpng/portfile.cmake
Labels: reviewed

#11250 [capstone] Update to 4.0.2
  ports/capstone/CONTROL
  ports/capstone/portfile.cmake
Labels: reviewed

#11242 [bitserializer-rapidyaml] Add new port
  ports/bitserializer-rapidyaml/CONTROL
  ports/bitserializer-rapidyaml/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11291 [nuspell] update port to v3.1.1
  ports/nuspell/CONTROL
  ports/nuspell/portfile.cmake
Labels: reviewed

#11173 Update zydis portfile.cmake
  ports/zydis/CONTROL
  ports/zydis/portfile.cmake
Labels: reviewed

#11287 [mpg123] Enable UWP support
  ports/mpg123/0004-add-arm64-uwp-config.patch
  ports/mpg123/CONTROL
  ports/mpg123/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11272 [ignition-msgs5][ignition-transport8] Add new ports 🤖
  ports/ignition-msgs5/CONTROL
  ports/ignition-msgs5/portfile.cmake
  ports/ignition-transport8/CONTROL
  ports/ignition-transport8/portfile.cmake
  scripts/ci.baseline.txt
Labels: needs-further-review, reviewed

#11265 [sdformat9] Add new port 🤖
  ports/sdformat9/CONTROL
  ports/sdformat9/portfile.cmake
  ports/sdformat9/respect-build-testing.patch
  scripts/ci.baseline.txt
Labels: reviewed

#11288 [glog] Disable tests
  ports/glog/CONTROL
  ports/glog/portfile.cmake
Labels: reviewed

#11200 [ceres] Added patch to add find_dependency() for suitesparse targets downstream
  ports/ceres/0003_fix_exported_ceres_config.patch
  ports/ceres/CONTROL
  ports/ceres/portfile.cmake
Labels: reviewed

#11279 [opus] Update port to 1.3.1-2
  ports/opus/CONTROL
  ports/opus/portfile.cmake
Labels: reviewed

#11270 [eigen3] [ignition-modularscripts] Fix installed pkgconfig files
  ports/eigen3/CONTROL
  ports/eigen3/portfile.cmake
  ports/ignition-cmake2/CONTROL
  ports/ignition-cmake2/portfile.cmake
  ports/ignition-fuel-tools1/CONTROL
  ports/ignition-fuel-tools1/portfile.cmake
  ports/ignition-modularscripts/CONTROL
  ports/ignition-modularscripts/ignition_modular_library.cmake
  ports/ignition-transport4/CONTROL
  ports/ignition-transport4/portfile.cmake
Labels: reviewed

#11254 [nlopt] Update to 2.6.2
  ports/nlopt/CONTROL
  ports/nlopt/portfile.cmake
Labels: reviewed

#11257 [libtorrent] add iconv feature on windows and clean up portfile
  ports/libtorrent/CONTROL
  ports/libtorrent/fix_find_iconv.patch
  ports/libtorrent/no_use_iconv.patch
  ports/libtorrent/portfile.cmake
Labels: reviewed

#11300 [otl] Update to 4.0.455
  ports/otl/CONTROL
  ports/otl/portfile.cmake
Labels: internal, reviewed

#11310 [string-theory] Update to 3.2
  ports/string-theory/CONTROL
  ports/string-theory/portfile.cmake
Labels: reviewed

#11316 [miniz] Fix broken cmake config file
  ports/miniz/CONTROL
  ports/miniz/portfile.cmake
Labels: internal, reviewed

#11314 [z3] update port to 4.8.8
  ports/z3/CONTROL
  ports/z3/fix-install-path.patch
  ports/z3/portfile.cmake
Labels: reviewed

#11311 [jsoncons] Update to v0.151.0
  ports/jsoncons/CONTROL
  ports/jsoncons/portfile.cmake
Labels: reviewed

#11308 [units] Update to 2.3.1
  ports/units/CONTROL
  ports/units/portfile.cmake
Labels: reviewed

#11074 [idevicerestore] Fix libgen.h cannot be found
  ports/idevicerestore/CONTROL
  ports/idevicerestore/fix-libgen.h-cannot-be-found.patch
  ports/idevicerestore/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9237 [kissfft] Add new port
  ports/kissfft/CMakeLists.txt
  ports/kissfft/CONTROL
  ports/kissfft/exports.def
  ports/kissfft/portfile.cmake
Labels: reviewed

#9126 [jaeger-client-cpp] New port
  ports/jaeger-client-cpp/CONTROL
  ports/jaeger-client-cpp/fix-CMakeLists.patch
  ports/jaeger-client-cpp/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#7005 [libmediainfo] Add new port
  ports/libmediainfo/CONTROL
  ports/libmediainfo/portfile.cmake
  ports/libmediainfo/vcpkg_support_in_cmakelists.patch
Labels: reviewed

#11280 [libpng] Fix android build
  ports/libpng/CONTROL
  ports/libpng/portfile.cmake
Labels: reviewed

#10972 [ompl] Fix patch apply error
  ports/ompl/CONTROL
  ports/ompl/fix-findeigen3.patch
  ports/ompl/portfile.cmake
Labels: internal, needs-further-review, reviewed

#11264 Improve Android doc (triplets, usage with cmake and prefab)
  docs/examples/vcpkg_android_example_cmake/.gitignore
  docs/examples/vcpkg_android_example_cmake/CMakeLists.txt
  docs/examples/vcpkg_android_example_cmake/compile.sh
  docs/examples/vcpkg_android_example_cmake/my_lib.cpp
  docs/examples/vcpkg_android_example_cmake_script/.gitignore
  docs/examples/vcpkg_android_example_cmake_script/CMakeLists.txt
  docs/examples/vcpkg_android_example_cmake_script/cmake/vcpkg_android.cmake
  docs/examples/vcpkg_android_example_cmake_script/compile.sh
  docs/examples/vcpkg_android_example_cmake_script/my_lib.cpp
  docs/index.md
  docs/specifications/prefab.md
  docs/users/android.md
  docs/users/triplets.md
Labels: needs-feature-review

#10871 [h5py-lzf] Add new port
  ports/h5py-lzf/0001-disable-H5PLget_plugin-api.patch
  ports/h5py-lzf/CMakeLists.txt
  ports/h5py-lzf/CONTROL
  ports/h5py-lzf/portfile.cmake
Labels: reviewed

#11093 [vcpkg] Fix nuget package import failed.
  toolsrc/src/vcpkg/export.cpp
Labels: reviewed

#11239 [vcpkg] Turn on tests in CI.
  scripts/azure-pipelines/azure-pipelines.yml
  scripts/azure-pipelines/linux/azure-pipelines.yml
  scripts/azure-pipelines/osx/azure-pipelines.yml
  scripts/azure-pipelines/windows/run-tests.yml
  scripts/bootstrap.sh
  toolsrc/CMakeLists.txt
  toolsrc/include/catch2/catch.hpp
  toolsrc/include/pch.h
  toolsrc/include/vcpkg-test/util.h
  toolsrc/include/vcpkg/base/json.h
  toolsrc/include/vcpkg/base/optional.h
  toolsrc/include/vcpkg/base/pragmas.h
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/include/vcpkg/dependencies.h
  toolsrc/include/vcpkg/statusparagraph.h
  toolsrc/src/vcpkg-test/plan.cpp
  toolsrc/src/vcpkg-test/system.cpp
  toolsrc/src/vcpkg-test/util.cpp
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/base/downloads.cpp
  toolsrc/src/vcpkg/base/files.cpp
  toolsrc/src/vcpkg/base/strings.cpp
  toolsrc/src/vcpkg/base/system.process.cpp
  toolsrc/src/vcpkg/binarycaching.cpp
  toolsrc/src/vcpkg/binaryparagraph.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.integrate.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/metrics.cpp
  toolsrc/src/vcpkg/statusparagraph.cpp
  toolsrc/vcpkglib/vcpkglib.vcxproj
  toolsrc/vcpkglib/vcpkglib.vcxproj.filters
Labels: infrastructure, internal, vcpkg bug

#10833 [microsoft-signalr] Add new port
  ports/microsoft-signalr/CONTROL
  ports/microsoft-signalr/portfile.cmake
Labels: reviewed

#11276 [sobjectizer] update to v.5.7.0.1.
  ports/sobjectizer/CONTROL
  ports/sobjectizer/portfile.cmake
Labels: reviewed

#11268 [llvm] add more backend options, fix issues
  ports/llvm/CONTROL
  ports/llvm/portfile.cmake
Labels: reviewed

#9402 [oatpp] Add new port
  ports/oatpp-consul/CONTROL
  ports/oatpp-consul/portfile.cmake
  ports/oatpp-curl/CONTROL
  ports/oatpp-curl/curl-submodule-no-pkg-config-in-vcpkg.patch
  ports/oatpp-curl/portfile.cmake
  ports/oatpp-libressl/CONTROL
  ports/oatpp-libressl/libress-submodule-downgrade-required-libressl-version.patch
  ports/oatpp-libressl/portfile.cmake
  ports/oatpp-mbedtls/CONTROL
  ports/oatpp-mbedtls/portfile.cmake
  ports/oatpp-swagger/CONTROL
  ports/oatpp-swagger/portfile.cmake
  ports/oatpp-websocket/CONTROL
  ports/oatpp-websocket/portfile.cmake
  ports/oatpp/CONTROL
  ports/oatpp/portfile.cmake
Labels: needs-further-review, reviewed

#8750 [gperftools] Add new port
  ports/gperftools/CMakeLists.txt
  ports/gperftools/CONTROL
  ports/gperftools/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10840 [imgui-sfml] Force imgui-sfml to be a static library
  ports/imgui-sfml/004-fix-find-sfml.patch
  ports/imgui-sfml/CONTROL
  ports/imgui-sfml/portfile.cmake
Labels: internal, needs-further-review

#11258 [gdcm] Update to version 3.0.5
  ports/gdcm/CONTROL
  ports/gdcm/portfile.cmake
Labels: internal, reviewed

#11294 [OpenGL] Fix lib files copy when VCPKG_BUILD_TYPE is set
  ports/opengl/CONTROL
  ports/opengl/portfile.cmake
Labels: reviewed

#11303 [libmysql] Update to 8.0.20
  ports/libmysql/CONTROL
  ports/libmysql/ignore-boost-version.patch
  ports/libmysql/linux_libmysql.patch
  ports/libmysql/portfile.cmake
  ports/libmysql/re2_add_compile_flags.patch
  ports/libmysql/system-libs.patch
  ports/libodb-mysql/CONTROL
  ports/libodb-mysql/fix-redefinttion.patch
  ports/libodb-mysql/portfile.cmake
Labels: internal, reviewed

#11325 [ogre/ogre-next] Add conflict error message
  ports/ogre-next/CONTROL
  ports/ogre-next/portfile.cmake
  ports/ogre/CONTROL
  ports/ogre/portfile.cmake
Labels: internal, reviewed

#11326 [Quill] update to v1.3.1
  ports/quill/CONTROL
  ports/quill/portfile.cmake
Labels: reviewed

#11327 [paho-mqttpp3] update to 1.1
  ports/paho-mqttpp3/CONTROL
  ports/paho-mqttpp3/fix-dependency.patch
  ports/paho-mqttpp3/fix-include-path.patch
  ports/paho-mqttpp3/portfile.cmake
Labels: reviewed

#11351 [gsl-lite] update to 0.37.0
  ports/gsl-lite/CONTROL
  ports/gsl-lite/portfile.cmake
Labels: reviewed

#11362 [uthenticode] Update to 1.0.4
  ports/uthenticode/CONTROL
  ports/uthenticode/portfile.cmake
Labels: reviewed

#11367 [restinio] update to v.0.6.8
  ports/restinio/CONTROL
  ports/restinio/portfile.cmake
Labels: reviewed

#11364 [tiff] Install runtime deps for tiff[tool]
  ports/tiff/CONTROL
  ports/tiff/portfile.cmake
Labels: reviewed

#11267 [sqlite3] Enable build for android
  ports/sqlite3/CMakeLists.txt
  ports/sqlite3/CONTROL
Labels: reviewed

#11332 [aws-sdk-cpp] Update to 1.7.333
  ports/aws-sdk-cpp/CONTROL
  ports/aws-sdk-cpp/CONTROL.in
  ports/aws-sdk-cpp/portfile.cmake
Labels: reviewed

#11339 [vcpkg] Avoid naming Policheck sensitive term 'Virgin Islands'
  toolsrc/src/vcpkg-test/large-json-document.json.inc
Labels: internal, vcpkg feature

#10915 [libpq] Update to 12.2 and some feature fixes
  ports/libpq/CONTROL
  ports/libpq/patches/windows/MSBuildProject_fix_gendef_perl.patch
  ports/libpq/patches/windows/Solution_Debug.patch
  ports/libpq/patches/windows/Solution_Release.patch
  ports/libpq/patches/windows/host_skip_openssl.patch
  ports/libpq/patches/windows/msgfmt.patch
  ports/libpq/patches/windows/openssl_exe_path.patch
  ports/libpq/patches/windows/python3_build_Debug.patch
  ports/libpq/patches/windows/python3_build_Release.patch
  ports/libpq/patches/windows/python_lib.patch
  ports/libpq/portfile.cmake
Labels: needs-further-review, reviewed

#11010 [libvmdk] Initial port
  ports/libvmdk/CMakeLists.txt
  ports/libvmdk/CONTROL
  ports/libvmdk/Config.cmake.in
  ports/libvmdk/no_fs_and_fadvise_on_macos.patch
  ports/libvmdk/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11072 [libxml2] Add iconv and charset linkage in vcpkg-cmake-wrapper on osx
  ports/libxml2/CONTROL
  ports/libxml2/vcpkg-cmake-wrapper.cmake
  scripts/ci.baseline.txt
Labels: needs-further-review, reviewed

#10717 [ctp] New port CTP library 6.3.15
  ports/ctp/CONTROL
  ports/ctp/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11355 [gSoap] Update to 2.8.102 and re-enable x64 Builds
  ports/gsoap/CONTROL
  ports/gsoap/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11368 [vcpkg] Do not build the metrics uploader with MSBuild when metrics are disabled
  scripts/bootstrap.ps1
  toolsrc/dirs.proj
Labels: needs-feature-review, reviewed

#11371 [qt5-base] Add Xorg dependency libx11-xcb-dev
  ports/qt5-base/CONTROL
  ports/qt5-base/portfile.cmake
Labels: internal, reviewed

#11388 [imgui] Update to 1.76
  ports/imgui/CONTROL
  ports/imgui/portfile.cmake
Labels: reviewed

#11393 [sciter] Update to 4.4.3.18.7817
  ports/sciter/CONTROL
  ports/sciter/portfile.cmake
Labels: reviewed

#11398 [nlopt] Enable UWP support
  ports/nlopt/0001-suppress-MS-compiler-complaint-about-negating-unsign.patch
  ports/nlopt/CONTROL
  ports/nlopt/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#11315 [vcpkg] Harden expand environment strings path with explicit integer overflow checks and resistance to CP_ACP.
  toolsrc/src/vcpkg/commands.edit.cpp
Labels: internal, vcpkg bug

#11263 [libgo] Update to 3.1
  ports/libgo/CONTROL
  ports/libgo/boost-168.patch
  ports/libgo/cmake.patch
  ports/libgo/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#11450 [vcpkg CI] Clean git directory before clone
  scripts/azure-pipelines/linux/azure-pipelines.yml
  scripts/azure-pipelines/osx/azure-pipelines.yml
  scripts/azure-pipelines/windows/azure-pipelines.yml
Labels: internal

#11432 [vcpkg] Harden file removals and clean directory contents in "CI" inside vcpkg itself.
  scripts/azure-pipelines/linux/initialize-environment.sh
  scripts/azure-pipelines/osx/initialize-environment.sh
  scripts/azure-pipelines/windows/azure-pipelines.yml
  scripts/azure-pipelines/windows/ci-step.ps1
  scripts/azure-pipelines/windows/initialize-environment.ps1
  toolsrc/include/vcpkg/base/files.h
  toolsrc/src/vcpkg/base/files.cpp
  toolsrc/src/vcpkg/commands.ci.cpp
Labels: infrastructure, internal, needs-further-review

#6780 [munit] Add new port
  ports/munit/CONTROL
  ports/munit/fix-install.patch
  ports/munit/portfile.cmake
  scripts/ci.baseline.txt
Labels: waiting for response

#11030 [ixwebsocket] update to 9.6.2
  ports/ixwebsocket/CONTROL
  ports/ixwebsocket/portfile.cmake
Labels: reviewed

#10767 [cmake] Update to 3.17.2
  ports/cpuid/CONTROL
  ports/cpuid/fix-install-headers.patch
  ports/cpuid/portfile.cmake
  ports/dmlc/CONTROL
  ports/dmlc/portfile.cmake
  ports/gts/portfile.cmake
  ports/libnice/CONTROL
  ports/libnice/portfile.cmake
  ports/magnum/CONTROL
  ports/magnum/portfile.cmake
  ports/metrohash/CMakeLists.txt
  ports/mlpack/CONTROL
  ports/mlpack/portfile.cmake
  ports/murmurhash/CMakeLists.txt
  ports/murmurhash/CONTROL
  ports/nanodbc/CONTROL
  ports/opencc/CONTROL
  ports/opencc/portfile.cmake
  ports/osg/portfile.cmake
  ports/podofo/CONTROL
  ports/podofo/portfile.cmake
  ports/replxx/CONTROL
  ports/replxx/portfile.cmake
  ports/stormlib/CMakeLists.txt
  ports/stormlib/CONTROL
  scripts/azure-pipelines/linux/provision-image.sh
  scripts/ci.baseline.txt
  scripts/vcpkgTools.xml
  toolsrc/src/vcpkg/tools.cpp
Labels: internal, needs-feature-review, vm update request

#11379 [parallelstl] update to 20200330
  ports/parallelstl/CONTROL
  ports/parallelstl/portfile.cmake
Labels: reviewed

#11433 [vcpkg] Optimize string split slightly.
  toolsrc/include/vcpkg/base/strings.h
  toolsrc/src/vcpkg-test/strings.cpp
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/base/files.cpp
  toolsrc/src/vcpkg/base/strings.cpp
  toolsrc/src/vcpkg/base/system.process.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/cmakevars.cpp
  toolsrc/src/vcpkg/commands.autocomplete.cpp
  toolsrc/src/vcpkg/commands.ci.cpp
  toolsrc/src/vcpkg/commands.porthistory.cpp
  toolsrc/src/vcpkg/logicexpression.cpp
Labels: internal, needs-further-review

#11394 [angle] update for gcc 10 compatibility
  ports/angle/001-fix-uwp.patch
  ports/angle/CMakeLists.txt
  ports/angle/CONTROL
  ports/angle/portfile.cmake
Labels: reviewed

#11397 [protobuf] protobuf v3.12.0
  ports/ignition-msgs5/01-protobuf.patch
  ports/ignition-msgs5/portfile.cmake
  ports/protobuf/CONTROL
  ports/protobuf/fix-uwp.patch
  ports/protobuf/portfile.cmake
Labels: reviewed

#11420 [parallel-hashmap] Update parallel-hashmap version
  ports/parallel-hashmap/CONTROL
  ports/parallel-hashmap/portfile.cmake
Labels: reviewed

#11426 [utfcpp] Update to 3.1.1
  ports/utfcpp/CONTROL
  ports/utfcpp/portfile.cmake
Labels: reviewed

#11435 [libgo] Update CONTROL file for typo
  ports/libgo/CONTROL
Labels: reviewed

#11437 [realsense2] Update to 2.34.0
  ports/realsense2/CONTROL
  ports/realsense2/fix-tools-compile-on-vs2019.patch
  ports/realsense2/portfile.cmake
Labels: internal, reviewed

#11449 [grpc] upgrade to 1.28.1
  ports/grpc/CONTROL
  ports/grpc/portfile.cmake
Labels: reviewed
