Repository microsoft/vcpkg, pull requests merged in 2020-03, with the labels that each got.

#10080 [fmt] Update to 6.1.2
  ports/fmt/CONTROL
  ports/fmt/fix-warning4189.patch
  ports/fmt/portfile.cmake
  ports/spdlog/CONTROL
  ports/spdlog/fix-include.patch
  ports/spdlog/portfile.cmake
Labels: reviewed

#10092 [sdl2] Fix CMake include directory
  ports/sdl2/CONTROL
  ports/sdl2/enable-winrt-cmake.patch
  ports/sdl2/fix-cmake-include-dir.patch
  ports/sdl2/portfile.cmake
Labels: reviewed

#10260 Upgrade Azure-Storage-CPP from 7.1.0 to 7.2.0
  ports/azure-storage-cpp/CONTROL
  ports/azure-storage-cpp/portfile.cmake
Labels: reviewed

#10246 [shogun] Fix target.cmake path
  ports/shogun/CONTROL
  ports/shogun/MSDirent.cmake
  ports/shogun/cmake-config.in.patch
  ports/shogun/fix-dirent.patch
  ports/shogun/portfile.cmake
Labels: internal, reviewed

#8426 [zydis] Update to v3.1.0
  ports/zydis/CONTROL
  ports/zydis/portfile.cmake
Labels: needs-further-review

#10290 Disable libhdfs3 and osg-qt in linux temporarily
  scripts/ci.baseline.txt
Labels: internal, reviewed

#10287 Fix log write failure when installing port for the first time
  toolsrc/src/vcpkg/build.cpp
Labels: internal

#10151 [nuspell] Add new port
  ports/nuspell/CONTROL
  ports/nuspell/cmake-disable-cli-and-docs.patch
  ports/nuspell/portfile.cmake
Labels: reviewed

#10291 [openmvs] use project install folder (#10265)
  ports/openmvs/CONTROL
  ports/openmvs/portfile.cmake
Labels: reviewed

#10303 [usockets] Add features
  ports/usockets/CMakeLists.txt
  ports/usockets/CONTROL
  ports/usockets/portfile.cmake
Labels: internal, reviewed

#10283 [google-cloud-cpp*] update to latest release
  ports/google-cloud-cpp-common/CONTROL
  ports/google-cloud-cpp-common/portfile.cmake
  ports/google-cloud-cpp-spanner/CONTROL
  ports/google-cloud-cpp-spanner/portfile.cmake
  ports/google-cloud-cpp/CONTROL
  ports/google-cloud-cpp/portfile.cmake
Labels: reviewed

#10281 [graphicsmagick] Updated to 1.3.35
  ports/graphicsmagick/CONTROL
  ports/graphicsmagick/portfile.cmake
Labels: reviewed

#10280 [darknet] update to latest release
  ports/darknet/CONTROL
  ports/darknet/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10276 [hyperscan] Update to version 5.2.1
  ports/hyperscan/CONTROL
  ports/hyperscan/portfile.cmake
Labels: reviewed

#10275 [doctest] Update to version 2.3.7
  ports/doctest/CONTROL
  ports/doctest/portfile.cmake
Labels: internal, reviewed

#10272 [googleapis] update to v0.5.0 release
  ports/googleapis/CONTROL
  ports/googleapis/portfile.cmake
Labels: reviewed

#10262 Upgrade uWebSockets to v0.17.2
  ports/uwebsockets/CONTROL
  ports/uwebsockets/portfile.cmake
Labels: reviewed

#10268 [openal-soft] Fix macOS builds
  ports/openal-soft/CONTROL
  ports/openal-soft/portfile.cmake
Labels: reviewed

#10083 [skia] add new port
  ports/skia/CONTROL
  ports/skia/portfile.cmake
  ports/skia/skiaConfig.cmake.in
  scripts/ci.baseline.txt
Labels: needs-further-review

#10242 [grpc] Update grpc to v1.27.3
  ports/grpc/CONTROL
  ports/grpc/portfile.cmake
Labels: reviewed

#8810 [healpix]Add new port.
  ports/healpix/CONTROL
  ports/healpix/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9911 [turbobase64] Add new port
  ports/turbobase64/CMakeLists.txt
  ports/turbobase64/CONTROL
  ports/turbobase64/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9930 [superlu] Add new port
  ports/superlu/CONTROL
  ports/superlu/fix-libm.patch
  ports/superlu/portfile.cmake
  ports/superlu/remove-make.inc.patch
  scripts/ci.baseline.txt
Labels: reviewed

#9942 [libcpuid] Add new port
  ports/libcpuid/CONTROL
  ports/libcpuid/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10301 [abseil] Add uwp support
  ports/abseil/CONTROL
  ports/abseil/fix-lnk2019-error.patch
  ports/abseil/fix-usage-lnk-error.patch
  ports/abseil/fix-uwp-build.patch
  ports/abseil/portfile.cmake
  ports/opencensus-cpp/CONTROL
  scripts/ci.baseline.txt
Labels: internal, needs-further-review

#10288 [azmq] Update to latest commit
  ports/azmq/CONTROL
  ports/azmq/portfile.cmake
Labels: internal, reviewed

#10111 [tinyfiledialogs] download from archive, not temporary ref
  ports/tinyfiledialogs/CONTROL
  ports/tinyfiledialogs/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10118 [pmdk] Update to 1.8
  ports/pmdk/CONTROL
  ports/pmdk/portfile.cmake
Labels: waiting for response

#10164 [murmurhash] Add new port
  ports/murmurhash/CMakeLists.txt
  ports/murmurhash/CONTROL
  ports/murmurhash/Config.cmake.in
  ports/murmurhash/portfile.cmake
  scripts/ci.baseline.txt
Labels: needs-further-review, reviewed

#10315 [folly] Fix dependency issue in config file
  ports/folly/CONTROL
  ports/folly/portfile.cmake
Labels: internal, reviewed

#10005 [upb] Fix uwp build
  ports/upb/CONTROL
  ports/upb/fix-uwp.patch
  ports/upb/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal

#10304 [vcpkg] Added command line switch --all-installed to allow exporting of all packages without needing to specify individual packages
  toolsrc/src/vcpkg/export.cpp
Labels: reviewed

#6214 Fix a import bug of nuget package, give priority to nuget package to set $(VcpkgRoot).
  toolsrc/src/vcpkg/export.cpp
Labels: needs-further-review

#7001 [zkpp] Add new port
  ports/zkpp/CMakeLists.txt
  ports/zkpp/CONTROL
  ports/zkpp/portfile.cmake
  ports/zookeeper/CONTROL
  ports/zookeeper/cmake.patch
  scripts/ci.baseline.txt
Labels: waiting for response

#9978 [python3] Modernize port + added --enable-shared
  ports/python3/CONTROL
  ports/python3/portfile.cmake
Labels: needs-further-review, reviewed

#10346 Update MSYS2 download source. Resolve #10322
  scripts/cmake/vcpkg_acquire_msys.cmake
Labels: needs-further-review

#10049 [MetroHash] Add new port
  ports/metrohash/CMakeLists.txt
  ports/metrohash/CONTROL
  ports/metrohash/Config.cmake.in
  ports/metrohash/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10357 [pegtl] Update 3.0.0-pre to most recent commit
  ports/pegtl/CONTROL
  ports/pegtl/portfile.cmake
Labels: reviewed

#10355 [argumentum] Update to 0.3.1
  ports/argumentum/CONTROL
  ports/argumentum/portfile.cmake
Labels: reviewed

#10354 [jsoncons] Update to v0.147.0
  ports/jsoncons/CONTROL
  ports/jsoncons/portfile.cmake
Labels: reviewed

#10351 [azure-storage-cpp] Update to 7.3.0
  ports/azure-storage-cpp/CONTROL
  ports/azure-storage-cpp/portfile.cmake
Labels: reviewed

#10309 [globjects] Fix incorrect filepath in globjects
  ports/globjects/CONTROL
  ports/globjects/portfile.cmake
Labels: reviewed

#10308 Fix tidy-html5 for non-Windows users
  ports/tidy-html5/CONTROL
  ports/tidy-html5/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10014 [ignition-cmake2] Add new port 🤖
  ports/ignition-cmake2/CONTROL
  ports/ignition-cmake2/portfile.cmake
  ports/ignition-cmake2/usage
  ports/ignition-modularscripts/CONTROL
  ports/ignition-modularscripts/ignition_modular_library.cmake
Labels: reviewed

#10018 [fltk] Fix build error on Linux
  ports/fltk/CONTROL
  ports/fltk/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#10025 [fcl] Update to 0.6.0
  ports/fcl/0001_fix_package_detection.patch
  ports/fcl/0002-fix_dependencies.patch
  ports/fcl/CONTROL
  ports/fcl/portfile.cmake
Labels: internal, reviewed

#10044 [hiredis] Fix feature ssl
  ports/hiredis/CONTROL
  ports/hiredis/fix-timeval.patch
  ports/hiredis/portfile.cmake
Labels: internal, reviewed

#10050 [loguru] Fix link issue
  ports/loguru/CONTROL
  ports/loguru/portfile.cmake
Labels: internal, reviewed

#10070 [mlpack ensmallen] Update to latest revision
  ports/ensmallen/CONTROL
  ports/ensmallen/disable_tests.patch
  ports/ensmallen/portfile.cmake
  ports/mlpack/CONTROL
  ports/mlpack/blas_lapack.patch
  ports/mlpack/cmakelists.patch
  ports/mlpack/portfile.cmake
Labels: internal, reviewed

#10040 [ixwebsocket] Update to 8.0.5
  ports/ixwebsocket/CONTROL
  ports/ixwebsocket/portfile.cmake
Labels: reviewed

#10104 [polyhook2] Update port
  ports/polyhook2/CONTROL
  ports/polyhook2/portfile.cmake
Labels: reviewed

#10106 [liblemon] Fix post-build failed
  ports/liblemon/CONTROL
  ports/liblemon/portfile.cmake
Labels: internal, reviewed

#10129 [cli11] Update to version 1.9.0
  ports/cli11/CONTROL
  ports/cli11/portfile.cmake
Labels: internal, reviewed

#10258 [ecsutil] Update ECSUtil v1.0.7.9
  ports/ecsutil/CONTROL
  ports/ecsutil/portfile.cmake
Labels: reviewed

#10302 Fix mhook build error.
  ports/mhook/fix-windows-packing-mismatch.patch
  ports/mhook/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10305 [suitesparse] Enable compiling SuiteSparse DLLs
  ports/suitesparse/CONTROL
  ports/suitesparse/portfile.cmake
Labels: reviewed

#10073 [freetype] Disabled Harfbuzz check for non-Windows platforms
  ports/freetype/CONTROL
  ports/freetype/portfile.cmake
Labels: reviewed

#10077 [gettext] fix build with mingw-w64
  ports/gettext/0003-Fix-win-unicode-paths.patch
  ports/gettext/CONTROL
  ports/gettext/config.win32.h
Labels: reviewed

#10154 Enable mbedtls's threading support for libssh
  ports/libssh/CONTROL
  ports/mbedtls/CONTROL
  ports/mbedtls/enable-pthread.patch
  ports/mbedtls/portfile.cmake
  ports/mbedtls/vcpkg-cmake-wrapper.cmake
Labels: needs-further-review, reviewed

#10333 [libgit2] Add features pcre,pcre2 to choose regex backend
  ports/libgit2/CONTROL
  ports/libgit2/portfile.cmake
Labels: reviewed

#10358 [cppgraphqlgen] Update to v3.1.1
  ports/cppgraphqlgen/CONTROL
  ports/cppgraphqlgen/portfile.cmake
Labels: reviewed

#10335 [pcre] Update to v8.44
  ports/pcre/CONTROL
  ports/pcre/fix-arm-config-define.patch
  ports/pcre/fix-arm64-config-define.patch
  ports/pcre/fix-option-2.patch
  ports/pcre/pcre-8.44_suppress_cmake_and_compiler_warnings-errors.patch
  ports/pcre/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10392 Add homepage for cli
  ports/cli/CONTROL
Labels: reviewed

#10057 [unixODBC] Add new port
  ports/unixodbc/CONTROL
  ports/unixodbc/portfile.cmake
  ports/unixodbc/unixodbcConfig.cmake
  ports/unixodbc/usage
  scripts/ci.baseline.txt
Labels: reviewed

#10068 [raylib] Update to 2.6.0
  ports/raylib/CONTROL
  ports/raylib/portfile.cmake
Labels: internal, reviewed

#9452 windows: set CMAKE_MSVC_RUNTIME_LIBRARY for cmake policy CMP0091
  scripts/toolchains/windows.cmake
Labels: needs-feature-review, reviewed

#10375 [vcpkg] Fix tool lookup without `which`
  toolsrc/src/vcpkg/base/files.cpp
Labels: internal

#10391 [googleapis] update to v0.6.0 release
  ports/googleapis/CONTROL
  ports/googleapis/portfile.cmake
Labels: reviewed

#10348 [community triplets] Add x64-osx-dynamic
  .gitignore
  triplets/community/x64-osx-dynamic.cmake
Labels: needs-further-review

#10378 [vcpkg] Implement a warning when running in a mismatched Visual Studio prompt
  toolsrc/include/vcpkg/base/optional.h
  toolsrc/include/vcpkg/base/system.h
  toolsrc/include/vcpkg/triplet.h
  toolsrc/src/vcpkg-test/optional.cpp
  toolsrc/src/vcpkg-test/system.cpp
  toolsrc/src/vcpkg/base/checks.cpp
  toolsrc/src/vcpkg/base/system.cpp
  toolsrc/src/vcpkg/install.cpp
  toolsrc/src/vcpkg/triplet.cpp
Labels: needs-feature-review

#10414 [angle] Add warning message
  ports/angle/CONTROL
  ports/angle/portfile.cmake
Labels: internal, reviewed

#10409 [mlpack] Fix build tool error
  ports/mlpack/CONTROL
  ports/mlpack/portfile.cmake
Labels: internal, reviewed

#10405 [zopfli] Update to 1.0.3
  ports/zopfli/CONTROL
  ports/zopfli/portfile.cmake
Labels: internal, reviewed

#10403 [realsense2] Fix tools installation issue
  ports/realsense2/CONTROL
  ports/realsense2/portfile.cmake
Labels: internal, reviewed

#10386 [sqlpp11-connector-mysql] Update to 0.29 to fix missing and unnecessary dependency of Boost.Thread on macOS
  ports/sqlpp11-connector-mysql/CONTROL
  ports/sqlpp11-connector-mysql/portfile.cmake
Labels: reviewed

#10443 [ci.baseline.txt] Mark tensorflow-cc as skip on OSX
  scripts/ci.baseline.txt
Labels: internal

#10445 [libpq][spdk-ipsec] Rebuild to correct baseline
  ports/libpq/portfile.cmake
  ports/spdk-ipsec/CMakeLists.txt
  ports/spdk-ipsec/CONTROL
  ports/spdk-ipsec/portfile.cmake
Labels: internal

#10366 [grpc][openssl][upb] Fix install on uwp
  ports/curl/CONTROL
  ports/grpc/portfile.cmake
  ports/grpc/snprintf.patch
  ports/libodb-mysql/CONTROL
  ports/libodb-mysql/portfile.cmake
  ports/openssl/CONTROL
  scripts/ci.baseline.txt
Labels: internal

#10367 [cpuid]Fix the naming mess
  ports/cpuid/CONTROL
  ports/cpuid/portfile.cmake
  scripts/ci.baseline.txt
Labels: needs-further-review

#10368 [ffmpeg] Fix build static error
  ports/ffmpeg/CONTROL
  ports/ffmpeg/portfile.cmake
Labels: internal, reviewed

#10062 [mimalloc] Update to 1.6.1
  ports/mimalloc/CONTROL
  ports/mimalloc/fix-cmake.patch
  ports/mimalloc/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#10032 [vcpkg] Compute ABIs upfront instead of just-in-time
  toolsrc/include/vcpkg/binarycaching.h
  toolsrc/include/vcpkg/build.h
  toolsrc/include/vcpkg/dependencies.h
  toolsrc/src/vcpkg/binarycaching.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.buildexternal.cpp
  toolsrc/src/vcpkg/commands.ci.cpp
  toolsrc/src/vcpkg/dependencies.cpp
  toolsrc/src/vcpkg/install.cpp
  toolsrc/vcpkglib/vcpkglib.vcxproj
  toolsrc/vcpkglib/vcpkglib.vcxproj.filters
Labels: internal

#10372 [vcpkg] Introduce Job Objects to improve ctrl-c performance on Windows
  toolsrc/include/vcpkg/base/system.process.h
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/base/system.process.cpp
  toolsrc/src/vcpkg/commands.env.cpp
Labels: internal

#10441 [spirv-tools] Update to version 2020.1
  ports/spirv-headers/CONTROL
  ports/spirv-headers/portfile.cmake
  ports/spirv-tools/CMake-targets.patch
  ports/spirv-tools/CONTROL
  ports/spirv-tools/cmake-install.patch
  ports/spirv-tools/comment-distutils.patch
  ports/spirv-tools/install-config-typo.patch
  ports/spirv-tools/portfile.cmake
Labels: reviewed

#10478 [cpprestsdk] Disable websockets by default.
  ports/cpprestsdk/CONTROL
  ports/signalrclient/CONTROL
Labels: reviewed

#10472 Correct parameter reference
  docs/examples/overlay-triplets-linux-dynamic.md
Labels: needs-further-review

#10456 [tbb] Update to new repository
  ports/tbb/CONTROL
  ports/tbb/portfile.cmake
Labels: internal, reviewed

#10437 [skia] Fix vswhere.exe can't find VS2017 with -sort
  ports/skia/CONTROL
  ports/skia/portfile.cmake
Labels: internal, reviewed

#9171 [ffmpeg] Add NVIDIA Codec feature for Windows and Linux
  ports/ffmpeg/CONTROL
  ports/ffmpeg/build.sh
  ports/ffmpeg/build_linux.sh
  ports/ffmpeg/portfile.cmake
  ports/ffnvcodec/CONTROL
  ports/ffnvcodec/build.sh
  ports/ffnvcodec/copyright
  ports/ffnvcodec/portfile.cmake
Labels: reviewed

#10453 [boost-process] Patch for header bug in boost 1.72
  ports/boost-process/CONTROL
  ports/boost-process/async_pipe_header.patch
  ports/boost-process/portfile.cmake
  scripts/boost/generate-ports.ps1
Labels: reviewed

#10477 [vcpkg-help] Reflow and small cleanups
  toolsrc/include/vcpkg/help.h
  toolsrc/src/vcpkg/help.cpp
  toolsrc/src/vcpkg/vcpkgcmdarguments.cpp
Labels: internal

#9862 [vcpkg] use _INIT flags in windows toolchain just like in the other toolchains
  scripts/toolchains/windows.cmake
Labels: reviewed

#10397 [vcpkg] Map configuration also for single configuration generators
  scripts/buildsystems/vcpkg.cmake
Labels: reviewed

#10557 [vcpkg] Improve common case of ignoring filesystem errors
  toolsrc/include/vcpkg/base/files.h
  toolsrc/include/vcpkg/base/ignore_errors.h
  toolsrc/src/vcpkg/base/files.cpp
  toolsrc/src/vcpkg/binarycaching.cpp
  toolsrc/vcpkglib/vcpkglib.vcxproj
Labels: internal

#10562 [vcpkg] Revert #9862 changes to fix crt check
  scripts/toolchains/windows.cmake
Labels: internal, reviewed

#10550 [realsense2] Update to version 2.33.1
  ports/realsense2/CONTROL
  ports/realsense2/portfile.cmake
Labels: internal, reviewed

#10540 [jsoncons] Update to v0.149.0
  ports/jsoncons/CONTROL
  ports/jsoncons/portfile.cmake
Labels: reviewed

#10546 [blitz] Update to the latest commit and fix no dll and lib generated
  ports/blitz/CONTROL
  ports/blitz/portfile.cmake
Labels: internal, reviewed

#10536 [catch2] Update to 2.11.3
  ports/catch2/CONTROL
  ports/catch2/portfile.cmake
Labels: internal, reviewed

#10526 [freerdp] Fix dynamic library path in cmake files
  ports/freerdp/CONTROL
  ports/freerdp/portfile.cmake
Labels: internal, reviewed

#10506 [exprtk] Update ExprTk package
  ports/exprtk/CONTROL
  ports/exprtk/copyright
  ports/exprtk/portfile.cmake
Labels: reviewed

#10486 [ffmpeg] Install tools
  ports/ffmpeg/CONTROL
  ports/ffmpeg/portfile.cmake
Labels: internal, reviewed

#10474 [Morton-nd] Update version to v3.0.0
  ports/morton-nd/CONTROL
  ports/morton-nd/portfile.cmake
Labels: reviewed

#10459 [wt] Update to 4.2.2
  ports/wt/CONTROL
  ports/wt/portfile.cmake
Labels: reviewed

#10451 [lzo] Fix for building Linux shared library
  ports/lzo/CONTROL
  ports/lzo/portfile.cmake
Labels: reviewed

#10446 [cppgraphqlgen] Update to v3.2.0 and fix #10407
  ports/cppgraphqlgen/CONTROL
  ports/cppgraphqlgen/portfile.cmake
Labels: reviewed

#10442 [spirv-cross] Update to version 2020-02-26
  ports/spirv-cross/CONTROL
  ports/spirv-cross/portfile.cmake
Labels: reviewed

#10436 [bfgroup-lyra] Update to 1.3
  ports/bfgroup-lyra/CONTROL
  ports/bfgroup-lyra/portfile.cmake
Labels: internal, reviewed

#10431 [civetweb] Add optional SSL support
  ports/civetweb/CONTROL
  ports/civetweb/portfile.cmake
Labels: reviewed

#10427 [lodepng] Update to commit e34ac0@2020-03-15
  ports/lodepng/CMakeLists.txt
  ports/lodepng/CONTROL
  ports/lodepng/algorithm.patch
  ports/lodepng/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#10426 [tinyexr] update to commit fdaeecb@2020-03-15
  ports/tinyexr/CONTROL
  ports/tinyexr/portfile.cmake
Labels: reviewed

#10399 [vcpkg] Add the possibility to load vcvars.bat with external toolchain.
  docs/users/triplets.md
  scripts/vcpkg_get_tags.cmake
  toolsrc/include/vcpkg/build.h
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/vcpkgpaths.cpp
Labels: reviewed

#10379 [vtk] Add find dependency pugixml in cmake config file
  ports/vtk/CONTROL
  ports/vtk/fix-pugixml-link.patch
  ports/vtk/portfile.cmake
Labels: internal, reviewed

#10325 [geotrans] Modify incorrect version in CONTROL
  ports/geotrans/CONTROL
Labels: internal, reviewed

#10274 [libpq] Fix build failure when vcpkg path contains spaces
  ports/libpq/CONTROL
  ports/libpq/portfile.cmake
Labels: reviewed

#10340 [ryu]Fix linux problem with ccache
  ports/ryu/CONTROL
  ports/ryu/portfile.cmake
Labels: reviewed

#10161 [ffmpeg] Disable vdpau in UNIX
  ports/ffmpeg/FindFFMPEG.cmake.in
  ports/ffmpeg/portfile.cmake
Labels: internal, reviewed

#10158 [magnum/magnum-plugins] Fix patches for --head builds
  ports/corrade/CONTROL
  ports/corrade/portfile.cmake
  ports/magnum-plugins/003-use-outdated-basisu.patch
  ports/magnum-plugins/CONTROL
  ports/magnum-plugins/portfile.cmake
  ports/magnum/001-tools-path.patch
  ports/magnum/002-sdl-includes-head.patch
  ports/magnum/002-sdl-includes.patch
  ports/magnum/CONTROL
  ports/magnum/portfile.cmake
Labels: reviewed

#10052 [replxx] Add new port
  ports/replxx/CONTROL
  ports/replxx/portfile.cmake
  ports/replxx/replxxConfig.cmake
  ports/replxx/usage
  scripts/ci.baseline.txt
Labels: reviewed

#8248 [abseil] Add compiler C++17.
  ports/abseil/CONTROL
  ports/abseil/portfile.cmake
Labels: internal, needs-further-review, reviewed

#9864 [hdf5] add tools and fortran feature
  ports/hdf5/CONTROL
  ports/hdf5/export-private.patch
  ports/hdf5/hdf5_config.patch
  ports/hdf5/portfile.cmake
  ports/hdf5/static-targets.patch
Labels: reviewed
