Repository microsoft/vcpkg, pull requests merged in 2020-01, with the labels that each got.

#9435 Update baseline
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9429 [simpleini] Install missing code
  ports/simpleini/CONTROL
  ports/simpleini/portfile.cmake
Labels: internal

#9508 [directxtk] Fix invalid solution configuration
  ports/directxtk/CONTROL
  ports/directxtk/portfile.cmake
Labels: internal, reviewed

#9503 [nameof] Update to 0.9.3
  ports/nameof/CONTROL
  ports/nameof/portfile.cmake
Labels: reviewed

#9494 [charls] upgrade to 2.1.0
  ports/charls/0001_cmake.patch
  ports/charls/CONTROL
  ports/charls/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9478 [argumentum] Add new port
  ports/argumentum/CONTROL
  ports/argumentum/portfile.cmake
Labels: reviewed

#9455 [ptext] Fix library cannot be found by find_package()
  ports/ptex/CONTROL
  ports/ptex/fix-config.cmake.patch
  ports/ptex/portfile.cmake
Labels: internal, reviewed

#9445 [fruit] fix wchar.h import issue under Catalina
  ports/fruit/CONTROL
  ports/fruit/portfile.cmake
Labels: reviewed

#9379 [uvatlas] Upgrade to dec2019
  ports/uvatlas/CONTROL
  ports/uvatlas/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9311 [freetype] use config and the correct alias
  ports/freetype/CONTROL
  ports/freetype/portfile.cmake
  ports/freetype/usage
Labels: reviewed

#9562 [glibmm] Fix build error on Linux
  ports/glibmm/CONTROL
  ports/glibmm/fix-thread.h.patch
  ports/glibmm/portfile.cmake
Labels: internal, reviewed

#9551 [libfreenect2] add opengl and opencl features
  ports/libfreenect2/CONTROL
  ports/libfreenect2/portfile.cmake
Labels: reviewed

#9547 [jsoncons] Update to 0.143.1
  ports/jsoncons/CONTROL
  ports/jsoncons/portfile.cmake
Labels: reviewed

#9543 [tabulate] Add new port
  ports/tabulate/CONTROL
  ports/tabulate/portfile.cmake
Labels: reviewed

#9535 [uwebsockets] Update to 0.17.0 alpha 4
  ports/uwebsockets/CONTROL
  ports/uwebsockets/portfile.cmake
Labels: internal, reviewed

#9529 [box2d] Update to 2019-12-31
  ports/box2d/CMakeLists.txt
  ports/box2d/CONTROL
  ports/box2d/export-targets.patch
  ports/box2d/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9519 [parallel-hashmap] Update to 1.30
  ports/parallel-hashmap/CONTROL
  ports/parallel-hashmap/portfile.cmake
Labels: reviewed

#9513 [wpilib] update to 2020.1.1
  ports/wpilib/CONTROL
  ports/wpilib/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9510 [check/gettimeofday] Move static libraries to manual-link
  ports/check/CONTROL
  ports/check/fix-lib-path.patch
  ports/check/portfile.cmake
  ports/gettimeofday/CMakeLists.txt
  ports/gettimeofday/CONTROL
  ports/gettimeofday/portfile.cmake
Labels: reviewed

#9502 [magic-enum] Update to v0.6.4
  ports/magic-enum/CONTROL
  ports/magic-enum/portfile.cmake
Labels: reviewed

#9499 [akali] Add new port
  ports/akali/CONTROL
  ports/akali/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9484 [simdjson] Update library
  ports/simdjson/CONTROL
  ports/simdjson/no_benchmark.patch
  ports/simdjson/portfile.cmake
Labels: reviewed

#9480 [cpp-httplib] Update library to 0.5.1
  ports/cpp-httplib/CONTROL
  ports/cpp-httplib/portfile.cmake
Labels: reviewed

#9448 [blend2d] Update to beta_2019-12-27
  ports/blend2d/CONTROL
  ports/blend2d/portfile.cmake
Labels: reviewed

#9443 [parallelstl] Update to latest version and fix find_package unable to find ParallelSTLConfig.cmake
  ports/parallelstl/CONTROL
  ports/parallelstl/fix-cmakelist.patch
  ports/parallelstl/fix-install-header.patch
  ports/parallelstl/portfile.cmake
Labels: internal, reviewed

#9428 [sdl2pp] Fix find dependencies
  ports/sdl2pp/CONTROL
  ports/sdl2pp/find-debug-libs.patch
  ports/sdl2pp/fix-dependencies.patch
  ports/sdl2pp/portfile.cmake
Labels: internal, reviewed

#9425 [basisu] update from upstream repository, add support for pvrtc2
  ports/basisu/CONTROL
  ports/basisu/portfile.cmake
Labels: reviewed

#9363 [grpc] Upgrade to gRPC-1.26.0
  ports/grpc/00001-fix-uwp.patch
  ports/grpc/00002-static-linking-in-linux.patch
  ports/grpc/00003-undef-base64-macro.patch
  ports/grpc/00005-fix-uwp-error.patch
  ports/grpc/00007-disable_grpcpp_channelz.patch
  ports/grpc/CONTROL
  ports/grpc/portfile.cmake
Labels: reviewed

#9341 [devil] fix OpenEXR not found
  ports/devil/0003_fix-openexr.patch
  ports/devil/CONTROL
  ports/devil/portfile.cmake
Labels: reviewed

#9301 [sdl1] Add build support for ARM64 Windows 10
  ports/sdl1/CONTROL
  ports/sdl1/SDL1_2017.sln
  ports/sdl1/SDL_dynamic.vcxproj
  ports/sdl1/SDLmain_dynamic.vcxproj
  scripts/ci.baseline.txt
Labels: reviewed

#9292 [libevent] Fix include headers fails on x64-windows, using CMAKE
  ports/libevent/CONTROL
  ports/libevent/fix-LibeventConfig_cmake_in_path.patch
  ports/libevent/portfile.cmake
Labels: internal, reviewed

#9308 [pdal] fix static build
  ports/pdal/CONTROL
  ports/pdal/fix-dependency.patch
  ports/pdal/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9158 [xsimd][xtensor][xtl] Update to lastest
  ports/xsimd/CONTROL
  ports/xsimd/portfile.cmake
  ports/xtensor-blas/CONTROL
  ports/xtensor-blas/portfile.cmake
  ports/xtensor-io/CONTROL
  ports/xtensor-io/portfile.cmake
  ports/xtensor/CONTROL
  ports/xtensor/portfile.cmake
  ports/xtl/CONTROL
  ports/xtl/portfile.cmake
Labels: needs-further-review

#8701 [nethost] Adding a port for nethost
  ports/nethost/0001-nethost-cmakelists.patch
  ports/nethost/0002-settings-cmake.patch
  ports/nethost/CONTROL
  ports/nethost/portfile.cmake
  ports/nethost/usage
  scripts/ci.baseline.txt
Labels: reviewed

#8707 [freeimage libraw] Fix case issue on Linux
  ports/freeimage/CMakeLists.txt
  ports/freeimage/CONTROL
  ports/freeimage/portfile.cmake
  ports/libraw/CONTROL
  ports/libraw/portfile.cmake
Labels: internal, reviewed

#8807 [cgl] Fix cgl cannot be found
  ports/cgl/CMakeLists.txt
  ports/cgl/CONTROL
  ports/cgl/portfile.cmake
Labels: internal, reviewed

#8813 [nanovg] Add dependency port stb
  ports/nanovg/CMakeLists.txt
  ports/nanovg/CONTROL
  ports/nanovg/portfile.cmake
Labels: internal, reviewed

#9043 [hdf5] Fix static builds when building dynamic builds
  ports/hdf5/CONTROL
  ports/hdf5/fix-generate.patch
  ports/hdf5/hdf5_config.patch
  ports/hdf5/portfile.cmake
Labels: internal, reviewed

#8650 [libmagic] Add new port
  ports/libmagic/CONTROL
  ports/libmagic/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9123 [many ports] Add mirror
  ports/cgicc/CONTROL
  ports/cgicc/portfile.cmake
  ports/gsl/CONTROL
  ports/gsl/portfile.cmake
  ports/libidn2/CONTROL
  ports/libidn2/portfile.cmake
  ports/libmicrohttpd/CONTROL
  ports/libmicrohttpd/portfile.cmake
  ports/libosip2/CONTROL
  ports/libosip2/portfile.cmake
Labels: internal, needs-further-review, reviewed

#9229 [libiconv] Make built libraries relocatable
  ports/libiconv/0001-Add-export-definitions.patch
  ports/libiconv/0003-Add-export.patch
  ports/libiconv/CMakeLists.txt
  ports/libiconv/CONTROL
  ports/libiconv/portfile.cmake
Labels: reviewed

#9098 [bullet3] Install CMake toolchain files and targets
  ports/bullet3/CONTROL
  ports/bullet3/cmake-fix.patch
  ports/bullet3/portfile.cmake
Labels: reviewed

#9121 [fmt] Disable warning C4189 on Visual Studio 2015
  ports/fmt/CONTROL
  ports/fmt/fix-warning4189.patch
  ports/fmt/portfile.cmake
Labels: internal, reviewed

#8891 [yas] Initial port
  ports/yas/CONTROL
  ports/yas/portfile.cmake
Labels: reviewed

#8122 [qpid-proton] Update to qpid-proton 0.29.0
  ports/qpid-proton/portfile.cmake
Labels: reviewed

#8386 [tfhe] Add new port
  ports/tfhe/CONTROL
  ports/tfhe/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#8518 [libb2] Add new port
  ports/libb2/CONTROL
  ports/libb2/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9107 [otl] Fix header file name and version number
  ports/otl/CONTROL
  ports/otl/portfile.cmake
Labels: internal, reviewed

#9194 [libaaplus] Add new port
  ports/libaaplus/CMakeLists.txt
  ports/libaaplus/CONTROL
  ports/libaaplus/portfile.cmake
Labels: reviewed

#9192 [liblzma] Stop exporting HAVE_CONFIG_H
  ports/liblzma/CMakeLists.txt
  ports/liblzma/CONTROL
Labels: internal, reviewed

#9054 [glib] Install msvc_recommended_pragmas.h to <vcpkg>/installed/include
  ports/glib/CMakeLists.txt
  ports/glib/CONTROL
  ports/glib/portfile.cmake
Labels: internal, reviewed

#8973 [curl] Disable export of Curl::curl targets when building 'tool' feature
  ports/curl/0007_disable_tool_export_curl_target.patch
  ports/curl/CONTROL
  ports/curl/portfile.cmake
Labels: internal, reviewed

#9579 [otl libaaplus forge] Fix build issues
  ports/forge/CONTROL
  ports/forge/portfile.cmake
  ports/libaaplus/CONTROL
  ports/libaaplus/portfile.cmake
  ports/otl/CONTROL
  ports/otl/portfile.cmake
Labels: internal, reviewed

#9605 Add December changelog
  CHANGELOG.md
Labels: internal

#9566 [vcpkg] Fix a typo
  toolsrc/src/vcpkg/build.cpp
Labels: reviewed

#9544 [reproc] Update to v10.0.3.
  ports/reproc/CONTROL
  ports/reproc/portfile.cmake
Labels: reviewed

#9537 [cpp-netlib] Fix cmake path, add homepage
  ports/cpp-netlib/CONTROL
  ports/cpp-netlib/portfile.cmake
Labels: internal, reviewed

#9437 [sqlite3] Rename sqlite3 tool as sqlite3.exe
  ports/proj4/CONTROL
  ports/proj4/portfile.cmake
  ports/sqlite3/CONTROL
  ports/sqlite3/portfile.cmake
Labels: internal, reviewed

#8934 [msix] Update to 1.7
  ports/msix/CONTROL
  ports/msix/fix-dependency-catch2.patch
  ports/msix/install-cmake.patch
  ports/msix/portfile.cmake
Labels: internal, reviewed

#7155 [xmsh]Upgrade version to 0.5.2 and fix build failure.
  ports/xmsh/CONTROL
  ports/xmsh/portfile.cmake
Labels: internal, reviewed

#6393 Map MinSizeRel and RelWithDebInfo correctly
  scripts/buildsystems/vcpkg.cmake
Labels: reviewed

#8920 [opencolorio] Modify find python2 to find python3
  ports/opencolorio/CONTROL
  ports/opencolorio/portfile.cmake
Labels: internal, reviewed

#9596 [graphicsmagick] Updated to GraphicsMagick-1.3.34
  ports/graphicsmagick/CMakeLists.txt
  ports/graphicsmagick/CONTROL
  ports/graphicsmagick/disable_graphicsmagick_modules.patch
  ports/graphicsmagick/portfile.cmake
Labels: reviewed

#9589 [curl] Update to 7.68.0
  ports/curl/0002_fix_uwp.patch
  ports/curl/CONTROL
  ports/curl/portfile.cmake
Labels: reviewed

#9583 [openal-soft] Update OpenAL Soft to 1.20.0
  ports/openal-soft/CONTROL
  ports/openal-soft/dont-export-symbols-in-static-build.patch
  ports/openal-soft/fix-arm-builds.patch
  ports/openal-soft/portfile.cmake
Labels: reviewed

#9576 [google-cloud-cpp] Upgrade to v0.17.0
  ports/google-cloud-cpp/0001-fix-x86-build.patch
  ports/google-cloud-cpp/CONTROL
  ports/google-cloud-cpp/portfile.cmake
Labels: reviewed

#9563 [openmvs] Update to 1.0.1
  ports/openmvs/CONTROL
  ports/openmvs/boost-1.71.patch
  ports/openmvs/cgal-5.0.patch
  ports/openmvs/glfw3_target_compat.patch
  ports/openmvs/portfile.cmake
Labels: reviewed

#9552 [otl] Update to version 4.0.451
  ports/otl/CONTROL
  ports/otl/portfile.cmake
Labels: reviewed

#9413 [HDF5] Correct SZIP linkage, modernize portfile
  ports/hdf5/CONTROL
  ports/hdf5/portfile.cmake
Labels: reviewed

#9397 [ixwebsocket] update to 7.6.3
  ports/ixwebsocket/CONTROL
  ports/ixwebsocket/portfile.cmake
Labels: reviewed

#9458 [azure-kinect-sensor-sdk] Remove feature test and fix static build in Windows
  ports/azure-kinect-sensor-sdk/CONTROL
  ports/azure-kinect-sensor-sdk/fix-components-path.patch
  ports/azure-kinect-sensor-sdk/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9361 [netcdf-c] Update to 4.7.3 and switched to use targets to generate valid targets
  ports/netcdf-c/CONTROL
  ports/netcdf-c/fix-build-error-on-linux.patch
  ports/netcdf-c/hdf5.patch
  ports/netcdf-c/hdf5_2.patch
  ports/netcdf-c/hdf5_3.patch
  ports/netcdf-c/portfile.cmake
  ports/netcdf-c/transitive-hdf5.patch
  ports/netcdf-c/use_targets.patch
Labels: reviewed

#9220 [realsense2] update to 2.30
  ports/realsense2/CONTROL
  ports/realsense2/fix-dependency-glfw3.patch
  ports/realsense2/portfile.cmake
Labels: internal, reviewed

#8936 [libplist] Update to 1.2.137
  ports/libplist/CMakeLists.txt
  ports/libplist/CONTROL
  ports/libplist/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#8880 [ismrmrd] Update to 1.4.1
  ports/ismrmrd/CONTROL
  ports/ismrmrd/fix-depends-hdf5.patch
  ports/ismrmrd/portfile.cmake
Labels: internal, reviewed

#8888 [caf] Update to 0.17.2
  ports/caf/CONTROL
  ports/caf/fix-arm.patch
  ports/caf/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#8824 [openmvg]Fix path in openmvg-config.cmake.
  ports/openmvg/CONTROL
  ports/openmvg/fix-config-cmake.patch
  ports/openmvg/portfile.cmake
Labels: internal, reviewed

#8683 [libwandio] Add new port
  ports/libwandio/CONTROL
  ports/libwandio/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#8678 [libevhtp] Add new port
  ports/libevhtp/CONTROL
  ports/libevhtp/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#8558 [cgicc]Fix usage error:lnk2019.
  ports/cgicc/CMakeLists.txt
  ports/cgicc/fix-static-build.patch
  ports/cgicc/portfile.cmake
Labels: internal, reviewed

#9625 [sfgui] fix sfgui on macOS
  ports/sfgui/001-fix-corefoundation-link.patch
  ports/sfgui/CONTROL
  ports/sfgui/portfile.cmake
Labels: reviewed

#9646 [azure-storage-cpp]Upgrade to 7.1.0
  ports/azure-storage-cpp/CONTROL
  ports/azure-storage-cpp/portfile.cmake
  ports/azure-storage-cpp/remove-gcov-dependency.patch
Labels: reviewed

#9669 [vcpkg] Update baseline for OSX
  scripts/ci.baseline.txt
Labels: internal

#9649 [tfhe] Fix Mac support
  ports/tfhe/CONTROL
  ports/tfhe/mac-fix.patch
  ports/tfhe/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9642 Introduce new policy to skip post verification of dll exports
  scripts/ports.cmake
  toolsrc/include/vcpkg/build.h
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/postbuildlint.cpp
Labels: needs-feature-review

#9602 [vcpkg] Fix build type in vcpkg_build_make.cmake [x264] Modernize
  ports/libosip2/CONTROL
  ports/x264/CONTROL
  ports/x264/portfile.cmake
  scripts/cmake/vcpkg_build_make.cmake
Labels: internal, needs-feature-review

#9536 Minor edit to help message for cli depend-info option. Fix for #9534.
  toolsrc/src/vcpkg/help.cpp
Labels: needs-feature-review

#9626 [glfw3] Update to 3.3.1
  ports/glfw3/CONTROL
  ports/glfw3/fix-config.patch
  ports/glfw3/portfile.cmake
Labels: reviewed

#9617 [akali] Update to v1.41
  ports/akali/CONTROL
  ports/akali/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9572 [soem] Add new port
  ports/soem/CONTROL
  ports/soem/portfile.cmake
  ports/soem/winpcap.patch
  scripts/ci.baseline.txt
Labels: reviewed

#9627 [glad] Update to 0.1.33
  ports/glad/CONTROL
  ports/glad/portfile.cmake
Labels: reviewed

#9636 [libxml2] Apply fixes also to the target of libxml2.
  ports/libxml2/CONTROL
  ports/libxml2/vcpkg-cmake-wrapper.cmake
Labels: reviewed

#9610 [gettext] Add dependency on iconv
  ports/gettext/CMakeLists.txt
  ports/gettext/CONTROL
Labels: reviewed

#9609 [xlnt] Upgrade to v1.4.0
  ports/xlnt/CONTROL
  ports/xlnt/portfile.cmake
  ports/xlnt/static-linking-for-windows.patch
Labels: reviewed

#9567 [cpr] Add find_dependency to cprConfig.cmake
  ports/cpr/CONTROL
  ports/cpr/cprConfig.cmake
Labels: reviewed

#9190 [sfml] Declare Windows library export
  ports/sfml/CONTROL
  ports/sfml/export-win-libs.patch
  ports/sfml/portfile.cmake
Labels: internal, reviewed

#7345 [libtorrent] Fix linkage issues for dynamic builds
  ports/libtorrent/CONTROL
  ports/libtorrent/portfile.cmake
Labels: internal, reviewed

#8895 [libffi] Add libffiConfigVersion.cmake file
  ports/libffi/CMakeLists.txt
  ports/libffi/CONTROL
Labels: needs-further-review, reviewed

#8817 [plplot] Fix static build issue
  ports/plplot/0001-findwxwidgets-fixes.patch
  ports/plplot/0005-wxwidgets-fix-rel-lib-dir.patch
  ports/plplot/CONTROL
  ports/plplot/fix_utils.patch
  ports/plplot/portfile.cmake
Labels: internal, needs-further-review, reviewed

#9051 [libpqxx] Fix lib name on Linux
  ports/libpqxx/CMakeLists.txt
  ports/libpqxx/CONTROL
Labels: internal, reviewed

#9155 [glui] Add new port
  ports/freeglut/CONTROL
  ports/freeglut/portfile.cmake
  ports/glui/CONTROL
  ports/glui/install-one-flavor.patch
  ports/glui/portfile.cmake
  ports/glui/vcpkg-cmake-wrapper.cmake
Labels: needs-further-review, reviewed

#9574 [doxygen] Updated to 1.8.17
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: reviewed

#9695 [ffmpeg] fix openssl detection
  ports/ffmpeg/0002-detect-openssl.patch
  ports/ffmpeg/CONTROL
Labels: reviewed

#9685 [catch2] Update to 2.11.1
  ports/catch2/CONTROL
  ports/catch2/portfile.cmake
Labels: internal, reviewed

#9372 [VCPKG] WinHTTPOption for company Proxy not correctly taken into account
  ports/python3/portfile.cmake
  toolsrc/src/vcpkg/base/downloads.cpp
Labels: needs-further-review

#9555 [embree3] added cleanup command to embree3 port for static build
  ports/embree3/CONTROL
  ports/embree3/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#7976 Community Triplets 🤝
  .gitignore
  docs/users/triplets.md
  toolsrc/VERSION.txt
  toolsrc/include/vcpkg/vcpkgpaths.h
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/build.cpp
  toolsrc/src/vcpkg/commands.autocomplete.cpp
  toolsrc/src/vcpkg/help.cpp
  toolsrc/src/vcpkg/vcpkgpaths.cpp
  triplets/community/arm-windows.cmake
  triplets/community/arm64-uwp.cmake
  triplets/community/x86-uwp.cmake
  triplets/community/x86-windows-static.cmake
Labels: internal

#9137 Add support for building with MinGW
  .gitignore
  scripts/cmake/vcpkg_common_definitions.cmake
  scripts/cmake/vcpkg_configure_cmake.cmake
  scripts/templates/portfile.in.cmake
  scripts/toolchains/mingw.cmake
  toolsrc/CMakeLists.txt
  toolsrc/include/pch.h
  toolsrc/include/vcpkg/base/files.h
  toolsrc/src/vcpkg.cpp
  toolsrc/src/vcpkg/base/hash.cpp
  toolsrc/src/vcpkg/base/system.cpp
  triplets/community/arm-mingw.cmake
  triplets/community/arm64-mingw.cmake
  triplets/community/x64-mingw.cmake
  triplets/community/x86-mingw.cmake
Labels: reviewed

#9684 [teemo] new port.
  ports/teemo/CONTROL
  ports/teemo/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9676 [libarchive] Update to 3.4.1
  ports/libarchive/CONTROL
  ports/libarchive/portfile.cmake
Labels: reviewed

#9630 [tinyfiledialogs] Fix tinyfiledialogs not being fetchable from sourceforge
  ports/tinyfiledialogs/CONTROL
  ports/tinyfiledialogs/portfile.cmake
Labels: reviewed

#9629 [tesseract] port update to 4.1.1 release
  ports/tesseract/CONTROL
  ports/tesseract/fix-text2image.patch
  ports/tesseract/portfile.cmake
Labels: reviewed

#9621 [glm] Updated to 0.9.9.7
  ports/glm/CONTROL
  ports/glm/portfile.cmake
Labels: reviewed

#9611 [google-cloud-cpp-spanner] Upgrade to the v0.5.0 release.
  ports/google-cloud-cpp-spanner/CONTROL
  ports/google-cloud-cpp-spanner/portfile.cmake
Labels: reviewed

#9591 [scintilla] Update to 4.2.3
  ports/scintilla/CONTROL
  ports/scintilla/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9752 [ppconsul] Add missing boost dependencies
  ports/ppconsul/CONTROL
  ports/ppconsul/portfile.cmake
Labels: reviewed

#9726 Fix osx baseline build failures
  ports/boost-signals/CONTROL
  ports/boost-signals/portfile.cmake
  ports/gtest/CONTROL
  ports/gtest/portfile.cmake
  ports/pcl/CONTROL
  ports/pcl/portfile.cmake
  ports/sfml/CONTROL
  ports/sfml/portfile.cmake
  ports/soil2/CONTROL
  ports/soil2/portfile.cmake
  ports/tmxparser/CONTROL
  ports/tmxparser/portfile.cmake
  ports/xerces-c/CONTROL
  ports/xerces-c/portfile.cmake
Labels: internal, reviewed

#9016 [ace] Let `ssl` feature able to work on Linux when selected
  ports/ace/CONTROL
  ports/ace/portfile.cmake
Labels: needs-further-review

#9777 [openssl] Update the version
  ports/openssl/CONTROL
  ports/openssl/portfile.cmake
Labels: reviewed

#9775 [libxlsxwriter] upgrade to 0.9.4
  ports/libxlsxwriter/0001-fix-cmake-file.patch
  ports/libxlsxwriter/CONTROL
  ports/libxlsxwriter/portfile.cmake
Labels: reviewed

#9767 [open62541] Update to v1.0
  ports/open62541/CONTROL
  ports/open62541/fix-install-bindir.patch
  ports/open62541/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9760 [monkeys-audio] Update to 5.14, add feature tools
  ports/monkeys-audio/CONTROL
  ports/monkeys-audio/portfile.cmake
  scripts/ci.baseline.txt
Labels: internal, reviewed

#9754 [mosquitto] Install mosquittopp.lib to dest
  ports/mosquitto/CONTROL
  ports/mosquitto/archive-dest.patch
  ports/mosquitto/portfile.cmake
Labels: internal, reviewed

#9787 [mqtt_cpp] Add new port
  ports/mqtt-cpp/CONTROL
  ports/mqtt-cpp/portfile.cmake
Labels: reviewed

#9773 Updating HPX to V1.4
  ports/hpx/CONTROL
  ports/hpx/portfile.cmake
Labels: reviewed

#9755 [opencolorio] fix lcms dependency
  ports/opencolorio/0001-lcms-dependency-search.patch
  ports/opencolorio/CONTROL
  ports/opencolorio/portfile.cmake
Labels: internal, reviewed

#9753 [paho-mqtt] Fix Windows platform predefined macros
  ports/paho-mqtt/CONTROL
  ports/paho-mqtt/fix-win-macro.patch
  ports/paho-mqtt/portfile.cmake
Labels: internal, reviewed

#9737 Update Alembic version to 1.7.12
  ports/alembic/CONTROL
  ports/alembic/portfile.cmake
Labels: reviewed

#9703 Update portfiles to use VCPKG_BUILD_TYPE
  ports/libudns/CONTROL
  ports/libudns/portfile.cmake
  ports/luajit/CONTROL
  ports/luajit/portfile.cmake
  ports/nmap/CONTROL
  ports/nmap/portfile.cmake
  ports/openssl-uwp/CONTROL
  ports/openssl-uwp/portfile.cmake
  ports/openssl-windows/CONTROL
  ports/openssl-windows/portfile.cmake
  ports/pfring/CONTROL
  ports/pfring/portfile.cmake
  ports/pfring/use-vcpkg-libpcap.patch
  ports/tcl/CONTROL
  ports/tcl/portfile.cmake
Labels: reviewed

#9770 [asmjit] update to current version
  ports/asmjit/CONTROL
  ports/asmjit/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9734 [libwebsockets] Update to v3.2.2
  ports/libwebsockets/CONTROL
  ports/libwebsockets/portfile.cmake
Labels: reviewed

#9732 [sobjectizer][so5extra] updates to 5.7.0 and 1.4.0
  ports/so5extra/CONTROL
  ports/so5extra/portfile.cmake
  ports/sobjectizer/CONTROL
  ports/sobjectizer/portfile.cmake
Labels: reviewed

#9725 [freeglut] Patch header correctly
  ports/freeglut/CONTROL
  ports/freeglut/portfile.cmake
Labels: reviewed

#9718 [ffmpeg] fix link order
  ports/ffmpeg/CONTROL
  ports/ffmpeg/FindFFMPEG.cmake.in
Labels: reviewed

#9713 [ppconsul] Upgrade to latest version
  ports/ppconsul/CONTROL
  ports/ppconsul/portfile.cmake
Labels: reviewed

#9708 [doxygen] Add alternative download URL
  scripts/cmake/vcpkg_find_acquire_program.cmake
Labels: reviewed

#9690 [string_theory] Update to 3.0
  ports/string-theory/CONTROL
  ports/string-theory/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9682 [anyrpc] Updated to latest commit
  ports/anyrpc/CONTROL
  ports/anyrpc/arm_endian_detection.patch
  ports/anyrpc/portfile.cmake
Labels: reviewed

#9680 [jasper] freeglut is not a dependency in macOS
  ports/jasper/CONTROL
  scripts/ci.baseline.txt
Labels: reviewed

#9633 [cryptopp] Fixed build error on ARM32/ARM64 Windows
  ports/cryptopp/CONTROL
  ports/cryptopp/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9573 [proj4] Update to version 6.3.0
  ports/proj4/CONTROL
  ports/proj4/disable-export-for-static-lib.patch
  ports/proj4/portfile.cmake
Labels: reviewed

#9557 [angle] Update to 2019-12-31
  ports/angle/001-fix-uwp.patch
  ports/angle/002-fix-builder-error.patch
  ports/angle/CMakeLists.txt
  ports/angle/CONTROL
  ports/angle/portfile.cmake
Labels: needs-further-review, reviewed

#9524 [msgpack11] Add new port
  ports/msgpack11/CONTROL
  ports/msgpack11/msvc.patch
  ports/msgpack11/portfile.cmake
Labels: reviewed

#9281 [pbc] Correct non Windows build
  ports/pbc/CONTROL
  ports/pbc/portfile.cmake
  scripts/ci.baseline.txt
Labels: reviewed

#9807 MinGW: Fix vcpkg common definitions
  scripts/cmake/vcpkg_common_definitions.cmake
Labels: reviewed

#9797 [gettext] fix library placement on macOS
  ports/gettext/CMakeLists.txt
  ports/gettext/CONTROL
Labels: reviewed

#9794 [fftw3] Fix SIMD compiler flag and mingw build failure
  ports/fftw3/aligned_malloc.patch
  ports/fftw3/fftw3_arch_fix.patch
  ports/fftw3/portfile.cmake
Labels: reviewed

#9779 [fizz] Update to latest version
  ports/fizz/CONTROL
  ports/fizz/fix-build_error.patch
  ports/fizz/portfile.cmake
Labels: reviewed

#9763 [azure-kinect-sensor-sdk] Fix *.dll install path
  ports/azure-kinect-sensor-sdk/CONTROL
  ports/azure-kinect-sensor-sdk/fix-components-path.patch
  ports/azure-kinect-sensor-sdk/portfile.cmake
Labels: reviewed

#9721 [netcdf-c] Fix builds with hdf5[parallel]
  ports/netcdf-c/CONTROL
  ports/netcdf-c/mpi.patch
  ports/netcdf-c/portfile.cmake
Labels: reviewed
