Repository microsoft/vcpkg, pull requests merged in 2021-10, with the labels that each got.

#19540 [vcpkg_configure_make] Standardize `OPTIONS` list item handling
  ports/libtasn1/portfile.cmake
  ports/libtasn1/vcpkg.json
  ports/python3/portfile.cmake
  ports/python3/vcpkg.json
  ports/starlink-ast/portfile.cmake
  ports/starlink-ast/vcpkg.json
  scripts/cmake/vcpkg_configure_make.cmake
  versions/baseline.json
  versions/l-/libtasn1.json
  versions/p-/python3.json
  versions/s-/starlink-ast.json
Labels: info:reviewed, category:tool-update, info:world-rebuild

#20210 [vcpkg_copy_tools] support copying .app bundles
  docs/maintainers/vcpkg_common_definitions.md
  scripts/cmake/vcpkg_common_definitions.cmake
  scripts/cmake/vcpkg_copy_tools.cmake
Labels: category:vcpkg-feature, info:reviewed

#20456 [reproc] Update port to 14.2.3
  ports/reproc/portfile.cmake
  ports/reproc/vcpkg.json
  scripts/ci.baseline.txt
  versions/baseline.json
  versions/r-/reproc.json
Labels: info:reviewed

#20518 [geogram, ccfits, chartdir] Build fixes discovered by CI on 2021-10-01
  ports/ccfits/portfile.cmake
  ports/ccfits/vcpkg.json
  ports/chartdir/portfile.cmake
  ports/chartdir/vcpkg.json
  scripts/ci.baseline.txt
  versions/baseline.json
  versions/c-/ccfits.json
  versions/c-/chartdir.json
Labels: category:port-bug, info:internal, category:infrastructure

#18460 [ffmpeg] Honor macosx deployment target for ffmpeg
  ports/ffmpeg/portfile.cmake
  ports/ffmpeg/vcpkg.json
  versions/baseline.json
  versions/f-/ffmpeg.json
Labels: category:port-feature, requires:author-response

#20488 [distorm] Update to 3.5.2b
  ports/distorm/CMakeLists.txt
  ports/distorm/fix-arm-builds.patch
  ports/distorm/portfile.cmake
  ports/distorm/vcpkg.json
  versions/baseline.json
  versions/d-/distorm.json
Labels: requires:author-response

#20838 Update vcpkg tool, add windows-arm64, and download rather than build on some POSIX
  scripts/bootstrap.ps1
  scripts/bootstrap.sh
  scripts/ci.baseline.txt
Labels: info:internal, category:infrastructure, category:tool-update
